mbta/realtime_signs

lib/signs/utilities/source_config.ex
priv/signs.json

**Asana:** [✅ realtime-signs changes for GL-B station consolidation](https://app.asana.com/0/584764604969369/1201236005519217)

feat: add signs for new B line stations

---

priv/signs.json

Reverts mbta/realtime_signs#503
Reverting the revert. This time I'll leave the PR unmerged until it's time for deploy 😬

Revert "Revert "Switch D and C berthing positions""

---

lib/content/audio/next_train_countdown.ex
lib/content/audio/predictions.ex
lib/content/message/predictions.ex
lib/content/utilities.ex
lib/signs/utilities/predictions.ex
priv/signs.json
test/content/audio/next_train_countdown_test.exs
test/content/messages/predictions_test.exs
test/signs/utilities/messages_test.exs

Reverts mbta/realtime_signs#519

Revert "Revert "Include platform info on JFK/UMass Mezzanine announcements""

---

lib/signs/utilities/source_config.ex
priv/signs.json

Changes based on findings mentioned [here](https://mbta.slack.com/archives/C03K6NLKKD1/p1664465186088269?thread_ts=1664397877.515509&cid=C03K6NLKKD1)

Add green routes to Lechmere source configs

---

.github/workflows/dev.yml
.github/workflows/prod.yml
config/config.exs
config/prod.exs
config/runtime.exs
lib/engine/alerts/station_config.ex

Adding github workflows to deploy to dev and prod on-prem clusters.
Also removing splunk logger backend from the prod config.

Workflows for deploying to on prem servers

---

.github/workflows/dev.yml

Had bad indentation on this gh workflow.

Fix indentation on workflow

---

README.md

Updating the README now that we've moved realtime-signs off of Opstech3

Update README after migration

---

lib/signs/bus.ex

**Asana Ticket:** [Handle config overrides for bus signs](https://app.asana.com/0/1201753694073608/1203913364994582/f)
This makes the bus signs respect the per-sign overrides in the config file. Also implements a special case for the Harvard lower sign.

handle bus sign overrides

---

config/runtime.exs
lib/realtime_signs_web/controllers/auth.ex
lib/realtime_signs_web/router.ex

The env variables have been added now so this is ok to deploy now

Revert "Revert "Add auth plug""

---

lib/engine/bus_predictions.ex

This implements a possible solution to memory overflow issues that have been happening over the last few days. Converts the bus predictions engine to use ETS instead of process state for storage. This mirrors how the other engines typically handle data. The hypothesis is that the built-in copying that ETS does will allow the original large JSON strings to be garbage collected sooner, reducing memory pressure.

convert bus predictions engine to use ets

---

.github/workflows/dev.yml

**Asana Ticket:** [Investigate the erl crash](https://app.asana.com/0/1201753694073608/1204416582520667/f)
Doubles memory from 1024M to 2048M.
Will monitor in dev before moving to prod

Increase memory in dev

---

lib/signs/bus.ex
test/signs/bus_test.exs

**Asana Ticket:** [Play "No bus service" at busways/transitway stops when all service is eliminated by alerts](https://app.asana.com/0/1201753694073608/1204324618353134/f)
This adds basic alert handling for bus signs. When no predictions are present, and the alert level indicates that the stop is closed, display and read "No bus service" instead of just showing a blank sign.

show no service message for bus alerts

---

lib/content/audio/approaching.ex
lib/content/audio/predictions.ex
lib/content/audio/train_is_arriving.ex
lib/content/message/predictions.ex

Reverts mbta/realtime_signs#677

Revert "Determine emptier car location and crowding description"

---

lib/signs/utilities/audio.ex

Reverts mbta/realtime_signs#715

Revert "Temporarily enable back bay and tufts"

---

lib/signs/utilities/audio.ex

Ad-Hoc
To be deployed around 8am on Monday morning (12/11/23) for an in-station demo

Enable crowding audio at Back Bay platform for 12-11 demo

---

lib/signs/utilities/audio.ex

Reverts mbta/realtime_signs#726

Revert "Enable crowding audio at Back Bay platform for 12-11 demo"

---

lib/content/message/predictions.ex

hotfix: treat unknown crowding as `:train_level`

---

lib/signs/utilities/messages.ex

Ad-hoc
Accidentally let this slip through my last PR

Remove io inspect

---

lib/engine/chelsea_bridge.ex

This addresses some recent sign process crashes. Currently, if the bridge API call is slow, it can tie up the engine process and cause callers to time out, resulting in sign process crashes. This changes the engine so it stores its state in ETS, which can be read without blocking.

convert bridge engine to use ets

---

lib/pa_ess/utilities.ex

**Asana Ticket:** [Create audio file for "Gallivan Blvd" bus headsign](https://app.asana.com/0/1185117109217413/1206517262772707/f)
See title.

add abbreviations and audio for Gallivan Blvd

---

.github/workflows/dev-green.yml
.github/workflows/dev.yml
.github/workflows/docker.yml
.github/workflows/prod.yml
Dockerfile
config/prod.exs
mix.exs

Reverts mbta/realtime_signs#739

Revert "Revert "Update dockerfile and actions""

---

priv/signs.json
scripts/one_offs/scu_ids.exs

**Asana Ticket:** [RTS: Sign ID -> SCU IP mapping](https://app.asana.com/0/1185117109217422/1206971421645898/f)
This adds SCU ids to `signs.json`. This change was made programmatically, via a script which is included for review. The came from the spreadsheet in the ticket.

add SCU ids to signs

---

.formatter.exs
config/config.exs
config/runtime.exs
scripts/one_offs/bus_config.exs

This changes the auto-formatter config to also apply to the `config` and `scripts` directories. The other diffs are the result of the formatting.

auto format scripts and configs

---

README.md

Just an addition to the README that covers an issue I ran into during initial setup.

docs: add note to README about JIT & Sonoma

---

lib/signs/bus.ex

**Asana Ticket:** [RTS: Trigger PA Message Readouts](https://app.asana.com/0/1185117109217413/1207286579042501/f)
Missed a change to bus audio that I needed to merge into the pa-messages branch. This PR is a hotfix to fix the compile error.

PA Messages quick fix

---

lib/signs/utilities/audio.ex

**Asana Ticket:** [Improve RTS PA Message logs](https://app.asana.com/0/1185117109217413/1208034429115013/f)
Added a function that formats PA Message structs into individual fields. This will make it easier to parse in Splunk when making the dashboard.

chore: Improve PA Message readout logs

---

.github/workflows/elixir.yml

**Asana Ticket:** [Update ubuntu version in RTS and signs-ui github actions](https://app.asana.com/0/1185117109217413/1209485133776275)
Use Ubuntu latest in Elixir CI workflow

Use ubuntu latest

---

lib/engine/alerts/api_fetcher.ex
lib/engine/alerts/fetcher.ex
lib/engine/alerts/station_config.ex
test/engine/alerts/api_fetcher_test.exs

While reviewing this code for the task [Investigate impact of alerts direction_id change in RTS](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210514559735248), I noticed some things that could apparently be simplified and types that could be better documented. See individual commits for details!

Alerts fetcher cleanup

---

lib/signs/utilities/messages.ex
test/signs/realtime_test.exs

**Asana Ticket:** [PA/ESS incorrect mezzanine content in overnight period](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1211060341609046?focus=true)
- In cases where we're in the overnight period, we'll now pass back an OvernightPeriod message which is similar to the Empty message but has a different usage within `tranform_messages`
- When we have a ServiceEnded and an OvernightPeriod, we'll now combine them into one ServiceEnded.

Fixed roll-up bug with Service Ended on mezzanine signs in Overnight Period

---

lib/signs/utilities/messages.ex

**Asana Ticket:** [Undo RL filtering on branches](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1205318778158693?focus=true)
Removed the previous Red Line filtering for large train time gaps

Remove Red Line filtering for Ashmont/Braintree branch stations

---

.github/workflows/asana.yml

**Asana Ticket:** [Asana integrations: Attach PR to story but don't move ticket ](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210237684564478?focus=true)
Sorry for all the state changes in this PR history. Had to draft->ready for review to test the updated secrets with the Asana workflow quite a bit, but the end result is working!

Update Asana workflow to only attach PR to ticket 
