lib/pa_ess/utilities.ex
priv/signs.json

**Asana Ticket:** [Updates to realtime-signs](https://app.asana.com/0/1199504266721641/1200959142579185/f)
This PR adds source configs for the new Lechmere and Union Square stations. Also adds a new headsign name in `PaEss.Utilities` for Union Sq, which will only be used for Lechmere until the new stations open for revenue service.

Add new glx stations

---

config/config.exs
lib/fake/httpoison.ex
test/headway/request_test.exs

**Asana Ticket:** Part of [💳 terraform-ize API and move to ECS](https://app.asana.com/0/584764604969369/1200732284152245)
As part of the ECS migration, we're moving to a new URL: https://api-dev-green.mbtace.com from https://green.dev.api.mbtace.com. I did a search of CTD's repos and found the old URL hardcoded in a few places.

chore: Update API dev-green URL

---

lib/content/audio/train_is_arriving.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_ess.ex
priv/signs.json

**Asana Ticket:** [Update Realtime Signs with new Message Ids](https://app.asana.com/0/1185117109217413/1201759923497483/f)
This PR adds new message Ids for audio messages that will be triggered by Realtime Signs for the new Union Square Terminus.
The two messages being added to the code map to **"Trains to Union Square"** and **"The next train to Union Square is now Arriving"** and can be referenced in this excel sheet https://mbta.sharepoint.com/:x:/s/CTD/ERDhKqom2ZVFv-w83p8_ZMMBVUsEiZwiuq23LUOmhI0srA?e=bIoD0j

Add trains to union square audio

---

priv/signs.json

Initially these sign zones were set up with having two sources for predictions. For one, we aren't giving predictions on GLX yet, and having two sources configured causes the headway messages for a sign to omit the headway direction. For example, the sign would show "Trains every 5 to 7 min" instead of "Heath St trains every 5 to 7 min.
This change updates the Union Sq zones to be single sourced so that they include "Heath St" for headway messages. We should be sure to loop back around to this and reconfigure the signs once we understand how predictions will be provided for this stop.
Asana Ticket filed for follow-up work once predictions are available: https://app.asana.com/0/1201753694073608/1201979909970000/f

Make union sq zones to be single source

---

lib/content/audio/train_is_boarding.ex
lib/content/utilities.ex
lib/pa_ess/utilities.ex
priv/signs.json
priv/stops.json
test/pa_ess/utilities_test.exs

**Asana Ticket:** [Update e-line with new headway directions to Union Square](https://app.asana.com/0/1185117109217413/1201714031001944/f)
This PR adds updates to the config and certain audio-related modules which will enable Union Square as a destination and headway direction on the E-Line for PA/ESS. This change shouldn't be deployed until revenue service is officially beginning, which is currently planned for March 21st, 2022.

Update headways for glx revenue service

---

README.md

Making edits to README.md to help clarify instructions on how to update environment variables.
This was brought up in a recent SEV when the idea of pointing Realtime Signs to the backup server was considered as an action to remediate the issue, but it was not well documented how to do this.

Add some more details around updating env variables

---

build_release.sh

The script used to build the release must also be updated to use Elixir 1.12
Fortunately, Elixir 1.12.3 is already present on opstech3 so we won't need to download it and put it there ourselves.

update build_release script to use elixir 1.12

---

priv/signs.json

**Asana Ticket:** [Handle Park Street WB berth changes](https://app.asana.com/0/1185117109217413/1202081491413707/f)
The berth switch is slated to start at the beginning of the Summer rating which is Sunday, June 19th. This PR adjusts the sign configurations for the sourcing of the data so that the text and audio will go to the new sign zones that will reflect the berth switch.
Formatting changes are also getting mixed into this PR which makes the count of changed lines quite high, but the only configs that were actually changed were for `park_st_westbound_wall_track` and `park_st_westbound_fence_track`.
Before switch (Screenshot from Signs UI dev):
After switch (Screenshot from running Realtime Signs branch and Signs UI locally):
Deployment should happen either very late on June 18th …

Switch D and C berthing positions

---

priv/signs.json

Reverts mbta/realtime_signs#502
Reverting this because I forgot that I have another PR that I plan to merge and deploy to prod before this one

Revert "Switch D and C berthing positions"

---

lib/monitoring/uptime.ex

**Asana Ticket:** [[health mon] Log full values for device_uptime fields](https://app.asana.com/0/1201786812162837/1202586894360138/f)
This change only affects the status logs for Sign and SCU monitoring. The station name can't include spaces if we want to include the full name in the Splunk Dashboard or in e-mail alerts and mentioned in the Asana ticket.

Replace space with underscore in station names

---

lib/content/utilities.ex
lib/fake/httpoison.ex

Specific pattern for the select D trains that are going to Union Sq. We need to add a new pattern because the usual default for D trains is North Station. We're using Science park because that's as far as we're predicting for these trains.

Union Square dest for D trains 

---

lib/monitoring/uptime.ex

ARINC is set up begin sending us online statuses of Live PA equipment so we should update the monitoring endpoint to parse these logs correctly and stream them into Splunk.
- DSP: Digital Signal Processor
- Amps: Amplifier
- Comrex: Comrex Live audio device

Enable logging of live PA equipment

---

lib/content/utilities.ex

Any train being predicted out to Science Park or Lechmere will use Union Sq as the headway destination

Trains predicted to Science Park or Lechmere to use Union Sq

---

lib/realtime_signs_web.ex
lib/realtime_signs_web/views/error_view.ex

We get periodic exceptions when ARINC sends us equipment statuses. From the looks of the logs, it seems like ARINC may be occasionally sending requests to the wrong routes, but we should also probably not completely fail when we get bad requests since this triggers alerts and creates noise in the digital-ride-alerts channel.
Example alert: https://mbta.slack.com/files/USLACKBOT/F03TCBLTJBG/splunk_alert__realtime_signs_prod_errors

Add error view

---

lib/content/audio/next_train_countdown.ex
lib/content/audio/predictions.ex
lib/content/message/predictions.ex
lib/content/utilities.ex
lib/signs/utilities/predictions.ex
priv/signs.json
test/content/audio/next_train_countdown_test.exs
test/content/messages/predictions_test.exs
test/signs/utilities/messages_test.exs

This PR adds some custom logic and message formatting for the JFK/UMass Mezzanine sign. We are currently in violation of ADA standards by not giving riders enough info about which platform the next train will be arriving at.
The solution is admittedly a bit hacky by accounting for the `RJFK-m` case specifically, but this station is very unique for the T both in how the tracks work but also in that the tracks are labeled as "Ashmont" and "Braintree" rather than "Track 1" and "Track 2". Therefore, I found that it made more sense to add some hard coded logic rather than come up with something more generalized.
Presentation [here](https://mbta.sharepoint.com/:p:/r/sites/CTD/_layouts/15/Doc.aspx?sourcedoc=%7B12779A90-381D-4630-90A3-EA835AADE74D%7D&file=7.29%20Recommendation.pptx&action=edit&mob …

Include platform info on JFK/UMass Mezzanine announcements

---

lib/content/audio/next_train_countdown.ex
lib/content/audio/predictions.ex
lib/content/message/predictions.ex
lib/content/utilities.ex
lib/signs/utilities/predictions.ex
priv/signs.json
test/content/audio/next_train_countdown_test.exs
test/content/messages/predictions_test.exs
test/signs/utilities/messages_test.exs

Reverts mbta/realtime_signs#517
Reverting this as it seems to be causing intermittent outages on this specific sign. ARINC is investigating but in the meantime, we are going to revert the feature and monitor the sign to see if things stabilize.

Revert "Include platform info on JFK/UMass Mezzanine announcements"

---

lib/monitoring/uptime.ex
lib/realtime_signs_web/controllers/monitoring_controller.ex

**Asana Ticket:** [Enable LivePA application status monitoring](https://app.asana.com/0/1201786812162837/1202938907907698/f)
ARINC is ready to send us Live PA software statuses alongside the current Sign, SCU, and audio equipment statuses they're sending us. This PR expands the module for logging these statuses to account for software components. I made the changes in a way where it would be easy to add the logging of additional software components, although there aren't necessarily plans to add anymore for the time being.
Example log of live PA software status:
`11:36:31.174 [info]  software_uptime: date_time=2022-09-07 10:52:14Z application=live_pa is_online=true status=RUNNING`

Enable monitoring of Live PA Software

---

lib/content/audio/next_train_countdown.ex
test/content/audio/next_train_countdown_test.exs

**Asana Ticket:** [Update next train arrival wording](https://app.asana.com/0/1201786812162837/1202857146305305/f)
We added a new message with wording that will improve clarity for platform arrival messages. This message is primarily used, if not exclusively, at JFK/UMass.
Old wording: `The next [stations] train on the [stations] platform [arrives/departs] in [x] minutes`
New wording: `The next [stations] train [arrives/departs] in [x] minutes on the [stations] platform`
Luckily, the new wording uses the same sound bites and parameters just in a different order, so the code changes are minimal.
From Andrew Daniels from ARINC explaining the message:
> The new message has been added to the system. It is MSG ID 98.
>
>The next [stations] train [arrives/departs] in [x] minutes on the …

Start using re-worded platform arrival message

---

lib/content/audio/approaching.ex
test/content/audio/approaching_test.exs

**Asana Ticket:** [Remove "The next orange line train is approaching with all new cars" from PA/ESS on the OL](https://app.asana.com/0/1185117109217422/1202942589486789/f)
This PR removes the use of the Message ID `785` which announces to riders that the approaching OL train has all new cars.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202963933316750

Remove logic for new OL trains

---

lib/monitoring/uptime.ex

ARINC is installing new DSPs that are apparently configured with a new `node_type` field with the value `BLU-80`. This PR updates the logic to handle this new value.
Additionally, the warn logs for unknown node types were triggering an existing, more general alert and causing noise. We can change it to an info log and create a new, more specific alert that I can edit since the more general alert is not owned by me.

Update logging module to handle new DSP type

---

config/runtime.exs
lib/pa_ess/logger.ex

Overrides default configs and uses the `PaEss.Logger` module as the sign updater module if an env variable `DRY_RUN` is set. 
This module has the same interface as `MessageQueue` which is used when we want to actually send http requests to the headend server. `MessageQueue` is the default for normal deploys to either dev or prod, but we can use this dry run feature when we are testing out deploying to the new on prem servers and don't want to risk potentially overwhelming the PAESS system with too many messages.

Add a dry run mode

---

priv/signs.json

**Asana Ticket:** [Add Bowdoin zone "W" to match what's installed](https://app.asana.com/0/1201786812162837/1203208997479587/f)
Adds source config for the Bowdoin drop off zone. This will enable realtime-signs to propagate messages to the ARINC headend server as well as Signs UI's renderings of the countdown clock.
Goes hand in hand with [this Signs UI PR](https://github.com/mbta/signs_ui/pull/855) and should be deployed soon after the Signs UI change is live

Add config for bowdoin dropoff zone

---

config/config.exs

**Asana Ticket:** [Change Realtime Signs to log in UTC](https://app.asana.com/0/0/1201681770685699/f)
This change is so that the logger for Realtime Signs is configured to log UTC time rather than local time.
Before:
After:

Update Realtime Signs to log UTC time

---

lib/content/utilities.ex

E trains are now running as non-revenue to Medford/Tufts, but were still using Union Sq as the headway direction for trains being predicted to Lechmere because of a past hot-fix.
We can also remove another artifact from a past hot-fix where we used Union Sq as the destination for trains that were only being predicted out til Science Park, but were going to Union Sq.
And finally, we should update the catch-all function definition for E-line trains that was initially set to union sq when GLX branch 1 first opened. This will be updated once again once Branch 2 opens to be Medford/Tufts

Trains predicted to 70501 will use Lechmere headway dest

---

config/runtime.exs
lib/jobs/message_latency_report.ex
lib/realtime_signs_web/controllers/monitoring_controller.ex
lib/realtime_signs_web/router.ex

**Asana Ticket:** [Outline the message latency evaluation steps & outputs](https://app.asana.com/0/1201786812162837/1203092194190502/f)
This job is responsible for generating daily ARINC message latency reports based on a provided start_date and days_to_analyze.
* start_date: The date from which the job should begin generating reports. The job
will work backwards from this date. Defaults to Date.utc_today() - 1 because those
will be the latest logs that we have when this job runs on its CRON schedule.
* days_to_analyze: The number of days to go back. This value will default to 7 because
we plan to schedule the job to run on a weekly basis.
The job downloads the zip file containing message latency log files for each station and calculates the 95th and 99th percentiles along with the total …

Message latency reporting job

---

lib/content/audio/vehicles_to_destination.ex
lib/content/utilities.ex
lib/pa_ess.ex
lib/pa_ess/utilities.ex
priv/signs.json

These changes only pertain to default values for signs set to headway mode 
- Headway mode for E Line only stations will use `Lechmere` as headway destination (Symphony and Prudential)
- Headway mode for Union Sq will use `Riverside` as headway destination because primarily D trains run out of there now
- Add `Inbound` and `Outbound` as possible values for headway destinations
- Green Line North Station will use `Inbound/Outbound`
- Science will use `Inbound/Outbound`
- Lechmere will use `Inbound/Outbound`
PIO Eryk Rotondo was made aware of and is ok with the use of Inbound/Outbound at these few stations https://mbta.slack.com/archives/C049FR1UQCV/p1667582256334679
Screenshots taken in dev:

Update headway destination values for E, GLX stations, and North Station

---

lib/jobs/message_latency_report.ex

Small tweak to make the default value for number of days to analyze for the message latency reporting job to be 1 day.
Running the job for 7 days worth of data at once is causing the heap to max out and the application to crash. Since we get logs from ARINC on a nightly basis and each report CSV that's generated is for one day's worth of data, there's no reason we can't just run the job on a nightly basis.
This PR changes the default value to 1 day to analyze so that when the job runs on it's CRON schedule, it just does the prior day.

Change default days to analzye to 1

---

lib/content/audio/vehicles_to_destination.ex

As a part of #544 we added inbound and outbound as possible values for headway destinations. The thing is, we were missing audio for "Inbound/outbound trains every [] to [] minutes". ARINC added new audio for these messages with message ids 197 and 198 respectively.

Add message_ids for inbound and outbout destinations

---

lib/signs/utilities/messages.ex
priv/stops.json

This config file affects how alerts are processed and applied to content displayed on countdown clocks.
Basically, we have to have the stops listed in sequence so that the logic can determine how the alert relates to the stop and therefore decide what content to choose. Without the list defined, the countdown clocks will just default to headway mode since there would be no predictions due to the alert (using a shuttle alert as an example here).
For an example of the logic working - if a stop is a where a shuttle alert begins, we blank out the clock to avoid misleading riders since we don't always know where the shuttles board whereas if a stop is along the route where the alert is in effect, we tell riders "No train service. Use shuttle bus".

Fix for alerts affecting B Line countdown clocks

---

priv/signs.json

**Asana Ticket:** [Blank countdown clocks on Ashmont drop-off platform display next 2 Mattapan Line departures](https://app.asana.com/0/1201786812162837/1203414051619270/f)
This PR adds the configuration necessary to have realtime-signs start sending Mattapan predictions to the Ashmont SB zone. The change goes hand-in-hand with this [Signs UI PR](https://github.com/mbta/signs_ui/pull/880)

Add configuration for RASH-s sign zone

---

lib/pa_ess/http_updater.ex
test/pa_ess/http_updater_test.exs

**Asana Ticket:** [Chore: Revisit max send rate](https://app.asana.com/0/1201753694073608/1203627766980881/f)
In Elixir, module attributes are evaluated at compile time. This means that `@max_send_rate_per_sec` and `@avg_ms_between_sends` were being calculated based on compile time values which are just the defaults. The config value that we actually want to use gets set at runtime instead, which means that those values were not being utilized.
This PR moves the calculation of these values to the initialization step of the http_updater GenServers so that we will evaluate them at runtime.

Calculate max send rate and avg wait time at runtime

---

lib/signs/utilities/predictions.ex
test/signs/utilities/predictions_test.exs

**Asana Ticket:** [Establish a fixed order of RL SB predictions for RL SB zones](https://app.asana.com/0/1201786812162837/1203617720856117/f)
This modifies the prediction logic to prefer showing distinct destinations when the prediction list has multiple destinations. This required moving the logic further down in the pipeline, since we want to choose based on the aggregated message `destination`, not the granular `destination_stop_id` that's in the raw prediction.
Tested by hardcoding some duplicate predictions and verifying that it treats them correctly.

prefer showing distinct destinations if a stop has multiple

---

priv/stops.json

**Asana Ticket:** [Investigate how alert conditions affect RTS messages](https://app.asana.com/0/1201753694073608/1203683812842466/f)
`stops.json` basically defines stop neighbors which helps Realtime Signs understand if a station should be considered a fully closed stop or a shuttle transfer stop when an active alert includes the stop_id. In this case, the stop_id for college ave eastbound was incorrectly set and therefore realtime signs incorrectly thought that the only neighboring stop for East Somerville was Gilman Sq when in reality, Gilman Sq is **College Ave's** neighbor.
By fixing the id, alerts should now be correctly applied to East Somerville.

Fix incorrect stop_id for college ave

---

lib/content/audio/next_train_countdown.ex
lib/content/audio/predictions.ex
lib/content/message/predictions.ex
test/content/messages/predictions_test.exs

Upon revisiting JFK/UMass predictions and doing a finer-grained analysis, we found that platform predictions at JFK/UMass tend to get less accurate after around the 5 minute threshold. This adjustment is a response to that research.
When the next Alewife train is more than 5 minutes away, we will use the "Platform TBD" message to encourage riders to wait in the mezzanine until the next train is closer.

Filter out JFK predictions > 5 min

---

test/engine/alerts_test.exs
test/engine/config_test.exs
test/engine/health_test.exs
test/engine/scheduled_headways_test.exs
test/pa_ess/http_updater_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Investigate and resolve intermittent health test errors](https://app.asana.com/0/1201753694073608/1203657802315715/f)
This should fix the intermittent failures on the health check test. The issue is a race condition, where we `send` a message to the module and then immediately check its logs for a response. This adds a short wait before checking, similar to how other tests handle this same situation.
This also reduces some unnecessarily long sleeps in the test code, which results in a ~1 second reduction in total time for `mix test` (3 sec down to 2 sec for me).
Also converts `:timer.sleep` to the more recent `Process.sleep`

fix health check test and speed up tests

---

lib/engine/bus_predictions.ex
lib/engine/scheduled_headways.ex
lib/realtime_signs.ex
lib/signs/bus.ex
lib/signs/supervisor.ex
lib/signs/utilities/signs_config.ex
scripts/transitway_engine/parse_config.exs
test/signs/utilities/signs_config_test.exs

**Asana Ticket:** [Create a new "bus" sign type](https://app.asana.com/0/1201753694073608/1203670096087486/f)
**Asana Ticket:** [Get bus predictions](https://app.asana.com/0/1201753694073608/1203670096087488/f)
This adds some initial pieces of the Transitway Engine code base:
* A new "bus" sign type to differentiate the behavior
* A module that downloads bus predictions
* A script that parses bulk data directly from the TE code
NOTE: None of the new modules are enabled by this PR, so this should be a no-op in production.

add bus sign type and get bus predictions

---

lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/utilities.ex

**Asana Ticket:** [Update audio announcements at Kenmore](https://app.asana.com/0/1201753694073608/1203674455933121/f)
This special case logic is aimed to help improve clarity for blind/low-vision riders at Kenmore, which has a unique platform setup and can sometimes be confusing to riders. The new logic will ensure that whenever we're announcing the next or following train at Kenmore that we include the branch letter along with it. So for example, we would announce something like "The next C train to Gov't center arrives in 2 minutes. The following D train to Union Square arrives in 4 minutes". We already announce the branch letter in the westbound direction so there would be no change there.
Example of an audio request announcing the next C train to Gov't Center
- …

Add special casing for Kenmore inbound announcements

---

lib/content/audio/no_service_to_destination.ex
lib/content/audio/vehicles_to_destination.ex
lib/content/message/alert/destination_no_service.ex
lib/content/message/alert/no_service_use_shuttle.ex
lib/content/message/headways/paging.ex
lib/headway/headway_display.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/headways.ex
lib/signs/utilities/messages.ex
priv/signs.json
test/content/audio/no_service_to_destination_test.exs
test/content/messages/alert/destination_no_service_test.exs
test/content/messages/alert/no_service_use_shuttle_test.exs
test/content/messages/headways/paging_test.exs
test/signs/utilities/audio_test.exs

**Asana Ticket:** [Mezzanine sign improvement for headways/alerts](https://app.asana.com/0/1201753694073608/1203773782529108/f)
This PR enables paging of headways on the second line of a countdown clock when there are predictions for the top line, only when the source configs are pinned to either line. This provides riders with some indication of service levels even when there are no live predictions for the second line.
The change also enables paging of "no service" or "no service, use shuttle" messages on the second line when there is an alert active in only one direction.
Paging will always happen on the second line to take advantage of the 6 extra characters.
A few example screen captures:
https://user-images.githubusercontent.com/16074540/214908943-7432ddf3-df9b-4f85-bf9c-fefbb2777706 …

Enable second line paging when headways or alerts

---

lib/content/message/bus_predictions.ex
lib/pa_ess/utilities.ex
lib/signs/bus.ex
scripts/transitway_engine/parse_config.exs

**Asana Ticket:** [Render predictions to signs / signs-ui](https://app.asana.com/0/1201753694073608/1203870383936974/f)
* Sends rendered predictions to the message queue, so they show up in signs-ui
* Shows next 2 predictions on single-route signs
* Suppresses route display in cases where it's unnecessary
* Pads route strings based on the longer one
NOTE: This code path is still not reachable with the current config, so it will have no impact in production for now.

send content strings to bus signs

---

lib/content/utilities.ex
lib/engine/bus_predictions.ex
lib/pa_ess/utilities.ex
lib/predictions/bus_prediction.ex
lib/signs/bus.ex

This moves a couple generic bus helpers out to the utility files to keep the main business logic clear. Also adds explicit types for bus predictions.

move bus helpers to utils and add prediction types

---

lib/signs/bus.ex
lib/signs/utilities/signs_config.ex
scripts/transitway_engine/parse_config.exs

**Asana Ticket:** [Implement mezzanine mode for bus signs](https://app.asana.com/0/1201753694073608/1203913364994578/f)
Adds mezzanine mode for bus signs. Currently this only affects a single sign (WTC mezzanine). This mode fetches two separate prediction lists and displays them independently. Updates the bus json schema with two new keys, `top_sources` and `bottom_sources`, which are used to configure the sign in this mode.

support mezzanine mode for bus signs

---

.github/workflows/dev.yml

ARINC has made their log collection more stable so we're now getting roughly 3x the data compared to before. (~38 MB on 2/8 compared to ~12 MB on 2/2 as a sample). We have a recurring nightly job that processes this data but it appears to be hitting memory limits and crashes given the example logs that happen when the job is scheduled to run:
```
2/9/23 8:15:58.352 AM | container_id=1928c824ed80 Crash dump is being written to: erl_crash.dump...done                                                                                                                                                                                                                                                     
2/9/23 8:15:26.351 AM | container_id=1928c824ed80 eheap_alloc: Cannot allocate 212907632 bytes of …
```

Increase task memory

---

.gitignore
config/dev.exs
lib/realtime_signs.ex
lib/signs/utilities/signs_config.ex
scripts/transitway_engine/parse_config.exs

This adds a flag that can be used to switch on the bus code paths, for ease of development. This is essentially what I've been doing locally, but this will make it easier to manage, especially as more pieces are added. The flag is explicitly documented everywhere, so should be easy to remove afterward.
Also adds arguments to the TE code parser to control what it generates.

add flag for testing bus code during development

---

lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/train_is_boarding.ex
lib/content/utilities.ex
test/content/audio/following_train_test.exs
test/content/audio/next_train_countdown_test.exs

**Asana Ticket:** [Update audio announcements ~at Kenmore~ on all of GL](https://app.asana.com/0/1201753694073608/1203674455933121/f)
This PR makes a change so that we _always_ announce the branch letter for Green Line trains. We already do this for westbound trains so this essentially expands the behavior for eastbound trains as well.

Announce branch letter at all gl stops

---

config/runtime.exs
lib/engine/chelsea_bridge.ex
lib/realtime_signs.ex
lib/signs/bus.ex
scripts/transitway_engine/parse_config.exs

**Asana Ticket:** [Handle Chelsea bridge logic](https://app.asana.com/0/1201753694073608/1203958349180920/f)
This adds a new engine to get the status of the Chelsea bridge, and displays that information on the relevant signs. The engine is disabled unless you're in "bus mode", and also requires setting a new environment variable with the encoded auth string, which can be found in the password vault.

handle Chelsea bridge status on bus signs

---

.github/workflows/dev.yml
lib/jobs/message_latency_report.ex

**Asana Ticket:** [Optimize Message latency job](https://app.asana.com/0/1201753694073608/1203923825770741/f)
This PR makes some memory optimizations to the message latency report job. Initially, I thought we might be able to batch process the CSVs but it turns out that it's primarily just one CSV that is causing the memory bottleneck which is the `all.csv` file that the script generates by combining all of the CSVs. Given the way percentiles work, we need all of the rows in memory so that we can sort them and calculate where the percentiles land and since `Enum.sort`'s space complexity is O(n), this single file uses the same amount of memory at one time as all of the others combined throughout the course of a run of the job. Therefore, batching likely won't be of much help here.
I did …

Optimize message latency report job

---

lib/pa_ess/http_updater.ex
lib/pa_ess/updater.ex
lib/signs/bus.ex

**Asana Ticket:** [Send bus audio messages](https://app.asana.com/0/1201753694073608/1204067334255204/f)
This closes the loop and sends out the computed bus audio messages on the specified schedule. Also corrects the predictions preamble for south station, and skips it if there are no predictions.

send scheduled bus audio messages

---

lib/signs/utilities/headways.ex

**Asana Ticket:** [New paging headways logic doesn't check against schedules data](https://app.asana.com/0/1201753694073608/1204118945498884/f)
This PR adds a check by calling `display_headways?` before deciding to show paging headways. The check uses schedules data to determine if we're within scheduled service hours and mirrors what we do for normal headway messages.
Tested by faking the current time as after service hours in the code itself. Result:

Add check before displaying paging headways

---

lib/engine/config.ex
test/engine/config_test.exs

This reworks the config engine test to abstract away knowledge of the underlying ETS tables. The goal is to free the tests from having to explicitly create tables during setup. This should reduce spontaneous failures when the internal implementation of the engine changes.

refactor config engine test

---

lib/engine/config.ex
lib/fake/external_config/local.ex
lib/pa_ess/utilities.ex
lib/signs/bus.ex
scripts/transitway_engine/parse_config.exs
test/engine/config_test.exs

This includes several smaller features:
* "Debounces" prediction times, to ensure that stale predictions are never revived later due to changes around the zero mark (see `prediction_stale?`)
* Suppresses all SL route names, as well as route names at Nubian A (per decision)
* Loads the Chelsea bridge flag from the config and uses it to control the bridge messages (see `bridge_enabled?`)
* Implements combined audio readout for both sides of Nubian E (see `extra_audio_sources`)
* Implements immediate bridge announcement at waterfront stops when the status changes to raised (see `should_announce_drawbridge?`)
* Fixes a math bug in the bridge status calculation

implement misc bus features

---

lib/content/message/alert/no_service_use_shuttle.ex
lib/content/message/headways/paging.ex
lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
test/content/messages/alert/no_service_use_shuttle_test.exs
test/content/messages/headways/paging_test.exs
test/content/messages/predictions_test.exs
test/content/messages/stopped_train_test.exs
test/pa_ess/http_updater_test.exs

**Asana Ticket:** [Stabilize paging frequency to address memory issues](https://app.asana.com/0/1201753694073608/1204168984928043/f)
This PR updates the few paging messages that we have to show each page for 4 seconds each (with the exception of JFK/UMass which we have set to page every 6 seconds) instead of 3 seconds. For background context: the "stops away" messages were set to show the first page for 6 seconds to convey that the primary piece of info is that the train is stopped. We decided internally to change this behavior so that each page shows for an equal duration.
The countdown clocks have been known to have their internal memory buffers overflow which causes crashes of unpredictable lengths.  Each page is sent by the SCU to the sign as an individual message at a frequency based …

Increase page durations for rail

---

lib/content/utilities.ex
lib/engine/bus_predictions.ex
lib/predictions/bus_prediction.ex
lib/signs/bus.ex
test/signs/bus_test.exs

* Uses API-provided headers to filter out responses that contain older data than we've gotten in previous responses. This fixes some instability in the prediction numbers over time.
* Includes trip id when identifying previous predictions. This accounts for the fact that we sometimes get predictions for future trips before the bus has passed on the current trip.
* Treats single-page messages as having a 6-second duration, for the purpose of delaying further updates. This will slow down sign updates in case we do encounter rapid changes in the predictions.

improve handling of bus prediction data

---

lib/signs/bus.ex
test/signs/bus_test.exs

This fixes a bug in the predictions sorting, where prediction timestamps were being sorted structurally instead of by-value. This only seemed to impact test code, which generates `DateTime` structs dynamically, whereas the parsed values from the API seemed to sort correctly despite the bug. Additionally, there was a bug in the test code that was asserting the wrong value, which masked the issue.

fix prediction sorting issue

---

lib/content/audio/closure.ex
lib/content/audio/custom.ex
lib/content/audio/following_train.ex
lib/content/audio/no_service_to_destination.ex
lib/content/audio/predictions.ex
lib/content/audio/stopped_train.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_ess/http_updater.ex
lib/pa_ess/logger.ex
lib/pa_ess/updater.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/reader.ex
test/content/audio/closure_test.exs
test/content/audio/custom_test.exs
test/content/audio/following_train_test.exs
test/content/audio/no_service_to_destination_test.exs
test/content/audio/predictions_test.exs
test/content/audio/stopped_train_test.exs
test/content/audio/vehicles_to_destination_test.exs
test/pa_ess/http_updater_test.exs
test/pa_ess/logger_test.exs
test/signs/utilities/audio_test.exs
test/signs/utilities/reader_test.exs

This standardizes the internal handling of audio message so that everything deals with lists of audio messages. This simplifies function signatures and eliminates the packing/unpacking of tuples in various places. Absence of audio is represented as `[]` instead of `nil`.

unify handling of multiple audios

---

lib/signs/realtime.ex
test/signs/realtime_test.exs

This fixes a bug that came out of the audio refactor. Passthrough train messages are sent via a separate code path, which wasn't updated to the new call spec.

fix passthrough train audio

---

lib/pa_ess/utilities.ex
lib/signs/realtime.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/headways.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex
lib/signs/utilities/signs_config.ex
lib/signs/utilities/source_config.ex
priv/signs.json
scripts/one_off/transform_signs.exs
test/content/audio/predictions_test.exs
test/signs/realtime_test.exs
test/signs/utilities/audio_test.exs
test/signs/utilities/headways_test.exs
test/signs/utilities/messages_test.exs
test/signs/utilities/predictions_test.exs
test/signs/utilities/reader_test.exs
test/signs/utilities/source_config_test.exs
test/signs/utilities/updater_test.exs

This aims to simplify the code that calculates headway messages. It does this by changing the structure of the signs JSON, and adding an explicit object under `source_config`, which holds the headway information alongside the prediction sources. Similar to before, platform signs have one config object, while mezzanine signs have a list of two. This allows for natural encodings of all existing cases, including the multiple headway groups at Ashmont. This results in simpler downstream logic for reading and interpreting the data.
Notes:
* The changes to `signs.json` were done entirely with the `transform_signs.exs` script, which is included here for review (but we can delete it afterward)
* This removes `source_for_headway`, since the headway configuration is now explicit and centralized. …

refactor headway code

---

README.md
config/dev.exs
lib/engine/bus_predictions.ex
lib/fake/httpoison.ex
lib/realtime_signs.ex
lib/signs/utilities/signs_config.ex
test/signs/utilities/signs_config_test.exs

This removes the `TEST_BUS_MODE` flag and enables the bus predictions and Chelsea bridge engines. These will fetch the relevant data in the background even though there are no enabled signs using them yet. After this, bus signs can be enabled one-by-one by adding entries to `signs.json`.
Also changes some code paths to behave correctly with empty data, and caches the list of bus stop ids on startup.

enable bus sign engines

---

priv/signs.json

This enables updates to courthouse signs. It will be deployed immediately after the signs are disabled in Transitway Engine. See https://github.com/mbta/transitway_engine/pull/1

enable courthouse for bus signs cutover

---

lib/message_queue.ex
test/message_queue_test.exs

**Asana Ticket:** [Investigate increasing message queue size](https://app.asana.com/0/1201753694073608/1204331493928462/f)
Increase the message queue size to 400 to prevent a bit of overflow on startup and to leave some extra buffer room + room for the new bus signs that are to be added.

Increase message queue size to 400

---

priv/signs.json

This enables Nubian platforms A and C for the bus signs cutover. It will be deployed alongside https://github.com/mbta/transitway_engine/pull/3

enable nubian A and C for bus signs cutover

---

lib/predictions/predictions.ex
test/predictions/predictions_test.exs

Restore reverse and terminal predictions for Red Line. Deploy pending on result of analysis. [Context in Slack ](https://mbta.slack.com/archives/C03K6NLKKD1/p1681224044867379)

Stop filtering Red Line predictions based on certainty

---

lib/pa_ess/utilities.ex

**Asana Ticket:** [Address >59 minutes readouts](https://app.asana.com/0/1201753694073608/1204383490284789/f)
This uses the generic audio takes for numbers from 60 to 100, where we don't have custom voice recordings. Some bus stops show predictions up to 75 minutes.

use generic audio for numbers > 59

---

priv/signs.json

**Asana Ticket:** [Deploy at scale](https://app.asana.com/0/1201753694073608/1204365079945497/f)
This enables all remaining bus signs, and will be deployed alongside https://github.com/mbta/transitway_engine/pull/4
Note that this change is simply additive, even if the diff makes it appear otherwise. You can perform a `--patience` diff locally to verify.

enable all bus signs for cutover

---

README.md
config/runtime.exs
config/test.exs
lib/engine/config.ex
lib/external_config/local.ex
lib/fake/external_config/local.ex
priv/config.json
test/external_config/local_test.exs

This leverages the recent signs-ui work to allow pointing at the config file of a local signs-ui. This enables a fully interactive local setup, where config changes in signs-ui are picked up and reflected in the sign output in real time, mirroring how the production system works.
Also removes support for the config file's "old format", which is no longer used.

allow pointing at local sign config

---

lib/message_queue.ex
lib/pa_ess/http_updater.ex
lib/pa_ess/updater.ex
test/message_queue_test.exs
test/pa_ess/http_updater_test.exs
test/signs/realtime_test.exs
test/signs/utilities/updater_test.exs

**Asana Ticket:** [Remove logic related to updating single lines for rail](https://app.asana.com/0/1201753694073608/1204460989217745/f)
Since we made messages always update both lines at the same time with #628 , we can remove all of the single line update logic.

Remove single line logic

---

.envrc.template
README.md
config/runtime.exs

This updates the documentation to specify using direnv to manage environment variables locally. This gives us a convenient way to include detailed inline documentation, and to suggest some values for wiring up the local environment without hard-coding them. Notes:
* Removed documentation for `SIGN_HEAD_END_HOST`, since this is handled by the config module now.
* Removed documentation for `NUMBER_OF_HTTP_UPDATERS`, on the premise that it's almost never necessary to modify this in practice.
* Removed the default value for `API_V3_URL` in `runtime.exs`, for consistency. Confirmed that both deployed environments will supply this via environment variables.

use direnv for local environment management

---

lib/signs/realtime.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex
test/signs/utilities/messages_test.exs
test/signs/utilities/predictions_test.exs

This extracts the rail prediction fetching to the top of the sign loop, and passes the predictions down to code paths that need them. This has two benefits:
* The data flow is clearer, due to centralizing access to external data sources.
* The predictions are only fetched once (rather than twice), so it's a bit more efficient.

centralize and deduplicate prediction fetching

---

lib/engine/config.ex
test/engine/config_test.exs

This changes the default sign behavior from 'auto' to 'off' if no explicit config is present. This matches what we show in signs_ui in this case, and provides a more conservative approach to adding new signs in the future. Also applies to the Chelsea bridge config.

default signs configs to off

---

lib/content/message/alert/no_service_use_shuttle.ex
lib/content/message/headways/paging.ex
lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
test/content/messages/alert/no_service_use_shuttle_test.exs
test/content/messages/headways/paging_test.exs
test/content/messages/predictions_test.exs
test/content/messages/stopped_train_test.exs
test/pa_ess/http_updater_test.exs

**Asana Ticket:** [ARINC investigates crashes seemingly caused by MZ dual-paging](https://app.asana.com/0/1201753694073608/1204553377557896/f)
This PR increases page durations to 5 seconds from 4 for rail-related paging messages. This is an effort to prevent signs from crashing when both lines of the sign are paging at the same time.  In the past when the JFK/UMass sign exhibited similar behavior, increasing the page duration stabilized the sign.
If we observe that signs still crash when the paging is at a 5 second interval, we can try 6. After 6 though, I feel that the pages may be getting too long and we'd probably want to consider other solutions.

Increase page duration to 5 seconds

---

lib/content/message/alert/no_service_use_shuttle.ex
lib/content/message/headways/paging.ex
lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
lib/headway/headway_display.ex
test/content/messages/alert/no_service_use_shuttle_test.exs
test/content/messages/headways/paging_test.exs
test/content/messages/predictions_test.exs
test/content/messages/stopped_train_test.exs
test/headway/headway_display_test.exs
test/pa_ess/http_updater_test.exs

**Asana Ticket:** [ARINC investigates crashes seemingly caused by MZ dual-paging](https://app.asana.com/0/1201753694073608/1204553377557896/f)
Increase page durations again to 6 seconds to see if this stabilizes double line paging for rail signs.
Now that pages are getting pretty long, we should stop increasing the durations and rely on ARINC addressing the issue at the SCU level if this doesn't work.

Increase page durations to 6 seconds

---

lib/message_queue.ex
lib/pa_ess/http_updater.ex
lib/pa_ess/updater.ex
lib/signs/bus.ex
lib/signs/realtime.ex
lib/signs/utilities/reader.ex
lib/signs/utilities/updater.ex
test/message_queue_test.exs
test/pa_ess/http_updater_test.exs
test/signs/bus_test.exs
test/signs/realtime_test.exs
test/signs/utilities/reader_test.exs
test/signs/utilities/updater_test.exs

**Asana Ticket:** [Add human readable logging to RTS messages for Transit Data](https://app.asana.com/0/1201753694073608/1204564881899172/f)
This PR introduces a change to pass the `sign_id` along so that we can log it when we send requests to ARINC. This is so that we can more easily query for requests that went to specific sign zones.
It also adds new fields for the top and bottom content to make it easier to parse out what was sent to a sign zone.

Add sign id to logs and make content more human-readable

---

lib/pa_ess/http_updater.ex
test/pa_ess/http_updater_test.exs

**Asana Ticket:** [Signs-UI shows a flag/toggle when audio has been sent to a zone](https://app.asana.com/0/1201753694073608/1204564881899174/f)
This sends audio messages to signs_ui, now that it can accept them. It consolidates the code paths for posting and logging messages, and fixes a case where we should have been logging `sign_id` but weren't.

send audio messages to signs-ui

---

lib/pa_ess/utilities.ex
lib/signs/bus.ex
test/pa_ess/utilities_test.exs

**Asana Ticket:** [Use 31-45 var messages when appropriate](https://app.asana.com/0/1201753694073608/1204612335144707/f)
This adds support for additional audio message ids recently added to the signs, with support for up to 45 vars. As of now, only some of the bus signs generate audios this long.

support up to 45 vars in audio messages

---

scripts/historical_analysis/closest_predictions.exs

This adds a script for investigating historical prediction values. It pulls raw data for the specified time period, performs the same kind of first-pass filtering as the app, and outputs a CSV showing a minute-by-minute breakdown of the closest prediction value for the given signs. This is useful to visualize the raw numbers we're receiving, to inform how we should transform them further.

add historical prediction analysis script

---

priv/stops.json

**Asana Ticket:** [Investigate Babcock alert treatment](https://app.asana.com/0/1201753694073608/1204800787143423/f)
Stemming from the above linked investigation, this PR adds a few new stops to the `stops.json` file for the B branch so that alerts that start between Kenmore and Amory get applied correctly to the countdown clocks as well as Babcock. Similarly add Northeastern so that Symphony gets proper treatment.
It also cleans up the file a bit and consolidates some of the lists. The lists for Green E and GLX don't need to be in the same list in order to work as intended.

Clean up stops.json and add new stops for B/E branches

---

lib/content/audio/vehicles_to_destination.ex
lib/content/message/headways/top.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/headways.ex

**Asana Ticket:** [Extend alert specificity to Headway visual and audio](https://app.asana.com/0/1201753694073608/1204971672094872/f)
Adds line specificity to mezzanine headway messages.
Example:
`Orange Line Trains`
`Every 5 to 7 min`

Add line specificity to mezzanine headway messages

---

lib/content/utilities.ex

Ad-hoc
Kenmore B stops were not included in the mapping from destination stop_ids to destinations so B branch predictions were defaulting to using `Boston Col` when the destination stop id was being calculated as `71151`. Went ahead and added the EB Kenmore platform id for the future.

Add Kenmore B stops as destinations

---

lib/signs/realtime.ex

**Asana Ticket:** [Investigate removing route-based filtering for predictions](https://app.asana.com/0/1201753694073608/1205057928541600/f)
This filtering appears to not be useful since there are always distinct platform stop ids for the distinct routes at a given station. We want to see how often, if at all, predictions are getting filtered out by route with this temporary logging.

Log route-based subway predictions filtering

---

lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/stopped_train.ex
lib/content/audio/train_is_boarding.ex
lib/pa_ess/utilities.ex

**Asana Ticket:** [Implement early AM prediction changes](https://app.asana.com/0/1201753694073608/1204795336662073/f)
While implementing early AM logic, the need for having pre-recorded takes for Southbound, Northbound, etc. came up so that we could use pre-recorded takes in order to read out times (e.g. 5:03 as "five-oh-three"). I'm not certain if ARINC's TTS would handle reading times correctly and we had the takes for time readouts already so it was simple enough to just add a couple more takes for the general headway directions instead.
This had an unintended side-affect of causing all normal prediction-style readouts from using the new takes as well rather than defaulting to an ad-hoc TTS readout. This would result in readouts such as "The next train to Southbound arrives in 5 …

Add takes for general headway directions

---

lib/content/audio/first_train_scheduled.ex
lib/content/message/custom.ex
lib/content/message/early_am/destination_scheduled_time.ex
lib/content/message/early_am/destination_train.ex
lib/content/message/early_am/scheduled_time.ex
lib/content/message/generic_paging.ex
lib/content/message/platform_prediction_bottom.ex
lib/content/utilities.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/audio.ex
test/content/audio/first_scheduled_train_test.exs
test/signs/utilities/audio_test.exs

**Asana Ticket:** [Implement early AM prediction changes](https://app.asana.com/0/1201753694073608/1204795336662073/f)
Add new content structs that will be used for early AM predictions suppreesion and related helpers/unit tests

Early AM predictions suppression content

---

lib/signs/realtime.ex
lib/signs/utilities/source_config.ex

**Asana Ticket:** [Investigate removing route-based filtering for predictions](https://app.asana.com/0/1201753694073608/1205057928541600/f)
This logic uses the `routes` fields in the source config for a stop to filter out predictions. This has caused a few instances, most recently for the new GLX stops, where trains that are being predicted in the feed do not show up on countdown clocks because the prediction is technically for a different route. A more specific example is an occasional Green Line B, C, or D train going up to Medford Tufts but not showing up on the countdown clocks because those signs source configs only had `Green-E` in the `routes` field.
In cases where there are multiple routes serving a station, there are always separate platform stop_ids that are used for each route …

Remove filtering subway predictions by route

---

priv/signs.json

**Asana Ticket:** [Expand Signs UI bulk headway section to separate E branch from GLX](https://app.asana.com/0/1201753694073608/1205175176761938/f)

New GLX Headway groups and set Lechmere/Science Park to use green_trunk

---

lib/signs/utilities/predictions.ex

**Asana Ticket:** [Filter out predictions near Braintree branch](https://app.asana.com/0/1201753694073608/1205175879397587/f)
See code comment and ticket for detailed background info.

filter red line predictions following schedule gaps

---

lib/signs/utilities/early_am_suppression.ex
test/signs/utilities/early_am_suppression_test.exs

**Asana Ticket:** [Implement early AM prediction changes](https://app.asana.com/0/1185117109217413/1204795336662073/f)
Fetching headways in RTS has some embedded logic that will fetch the first and last scheduled arrivals and compare the current time against them to see if headways should be shown or not. This logic is performed at the **sign** level rather than the source level.
In the early AM hours, this sign-level logic is causing both lines/sources of mezzanine signs to go to headways when one of the lines should have stayed on a timestamp message.
This PR adds some additional logic that does a check of the current time + upper headway range against the scheduled first arrival for the specific sources. If the headways should be active, then the logic passes on the headway messages. …

Add logic to compare to scheduled first arrival

---

lib/signs/utilities/predictions.ex

**Asana Ticket:** [Refine RL prediction filtering](https://app.asana.com/0/1185117109217413/1205285065466009/f)
This increases the threshold for filtering red line prediction "gaps" from 18 to 21 minutes.

increase red line gap filtering

---

test/signs/realtime_test.exs

This adds a "factory" style helper function for generating predictions for test cases. It provides default values and abstracts over a few key concepts like destination, which dramatically shortens the calling code.
Note that a few cases were rewritten to eliminate redundant testing of some logic.

generate test predictions via factory function

---

lib/predictions/predictions.ex
test/predictions/predictions_test.exs

https://app.asana.com/0/1205101743911491/1205386558729560/f
This suppresses terminal and reverse predictions for the red line. Note that this code was borrowed and modified from #611

suppress terminal and reverse predictions for RL

---

lib/content/audio/approaching.ex
lib/content/audio/predictions.ex
lib/content/audio/train_is_arriving.ex
lib/content/message/predictions.ex
lib/engine/locations.ex

Reverts mbta/realtime_signs#684
Errors were occurring in Dev because the `multi_carriage_details` field is still only in dev-green and that was causing `get_crowding_description` to attempt to call `Enum.map(nil)`.
Adding a default of `[]` to the parsing logic. Tested against the prod RTR feed to make sure there are no errors.

Revert "Revert "Determine emptier car location and crowding description""

---

lib/headway_analysis/server.ex

The headway accuracy logging was using UTC timestamps, which caused it to report the wrong headway values around the peak/off-peak transition.

fix time zone bug in headway accuracy logging

---

lib/content/audio/approaching.ex
lib/content/audio/train_is_arriving.ex
test/content/audio/approaching_test.exs
test/content/audio/train_is_arriving_test.exs

This fixes an issue with the audio messages for OL crowding. With the included "space" var, the total number of vars is 3, which corresponds to message id "105", not "104". Switching to `Utilities.take_message` handles this mapping and the addition of the space automatically.

fix message id for crowding audio

---

lib/content/audio/approaching.ex
lib/content/audio/train_is_arriving.ex
test/content/audio/approaching_test.exs
test/content/audio/train_is_arriving_test.exs

This turns off generation of crowding audio for now, so we can deploy the rest of the code in the meantime. We can revert this PR when we're ready to enable it.

disable crowding audio messages

---

lib/pa_ess/http_updater.ex

**Asana Ticket:** [Improve send_audio logging in Splunk](https://app.asana.com/0/1185117109217413/1205407137195560/f)
Include the type of audio struct that a message is being derived from in our `send_audio` and `send_custom` audio logs.
Also include a string representation of any fields and their values that belong to the struct.

Add more detailed audio logging

---

.github/workflows/dev-green.yml

Adds a new GH workflow for deploying to Realtime Signs dev-green.
Note: The dev-green environment is not set up yet as of 9/12. Currently working with infra to do that.

Add workflow for deploying to dev-green

---

lib/content/audio/predictions.ex
lib/content/message/platform_prediction_bottom.ex
lib/content/message/predictions.ex
lib/content/utilities.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/predictions.ex
test/content/audio/next_train_countdown_test.exs
test/content/audio/predictions_test.exs
test/content/messages/predictions_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Replace 20+ min with actual predictions](https://app.asana.com/0/1185117109217413/1203830107648831/f)
See ticket for complete description. Additional notes:
* Fixes an issue where we were inadvertently doing immediate audio announcements of 20+ predictions.
* Fixes an edge case where predictions with nil arrival or departure times would always suppress stopped status.

replace 20+ minutes with actual predictions

---

.github/workflows/dev-green.yml
config/runtime.exs
lib/engine/config.ex
lib/external_config/s3.ex

We need to bind the dev-green container to a different port as port 80 is already being used by dev. Tested the workflow from the branch and was able to successfully deploy the instance.
Upon doing this, I started seeing 403 errors in Splunk indicating that Realtime Signs dev-green wasn't able to read the config file from S3. I realized that the resource list for S3 needed to be updated in Terraform to allow Realtime Signs to read the file.
While making the Terraform update, I also decided to make a similar change for the `headend.json` file that we keep in S3. This file was added fairly recently to let us manage what headend server Realtime Signs sends messages through via S3. For dev-green, the IP for the headend server should be `nil` because there is no dev-green equivalent amongst …

Fix dev green deploys

---

lib/content/audio/boarding_button.ex
lib/content/audio/predictions.ex
lib/content/message/predictions.ex
lib/signs/utilities/predictions.ex
test/content/messages/predictions_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Record and implement new audio at Bowdoin (trains to Wonderland)](https://app.asana.com/0/1185117109217413/1204757955138830/f)
This adds a special announcement to boarding messages at Bowdoin eastbound.

read special boarding button announcement at Bowdoin

---

lib/content/audio/approaching.ex
lib/content/audio/train_is_arriving.ex
lib/signs/utilities/audio.ex
test/content/audio/approaching_test.exs
test/content/audio/train_is_arriving_test.exs
test/signs/utilities/audio_test.exs

This reverts commit 87da0b4bcfcf2751ed38423e078877672b0639d5.
Enable crowding audio but limit it to a few stations for field testing purposes.

Revert 688 bhw/disable crowding

---

lib/signs/utilities/audio.ex
test/signs/utilities/audio_test.exs

For turning off OL crowding once field testing is done but keep logic in case we need to turn on another individual station later.
The call to `Enum.map` can be fully removed once OL crowding goes fully live.

Turn off OL crowding

---

lib/content/message/predictions.ex
lib/signs/utilities/predictions.ex
test/content/messages/predictions_test.exs

Mezzanine zones should be omitted from announcing crowding information.
[Slack message](https://mbta.slack.com/archives/G012H4G4U06/p1695067847876489?thread_ts=1695065179.307539&cid=G012H4G4U06) for context

Exclude mezzanine zones from crowding announcements

---

lib/content/utilities.ex
priv/signs.json

**Asana Ticket:** [Add stop IDs for new GL terminal predictions](https://app.asana.com/0/1185117109217413/1205396140780846/f)
According to the Glides team, the places that will start having Glides-based predictions are:
- Boston College
- Cleveland Circle
- Riverside
- Union Square
- Medford/Tufts
- Mattapan
We only have countdown clocks at Riverside, Union Sq, and Medford/Tufts out of this list.
The configuration won't need to change for Medford Tufts or Riverside with the exception of starting to announce boardings.
The Union Sq platforms each serve both directions so they have special platform stop ids that help us tell riders which track a train is predicted to leave from. This is the same setup that we use at most heavy rail terminals.

Prepare for supporting GL Terminal predictions

---

priv/signs.json

Ad-hoc:
Brookline Village was still using North Station as the headsign. This was probably just an oversight from back when we first started sending predictions to GLX signs.

Change Brookline Village to use Union Sq headsign

---

lib/engine/alerts.ex
lib/engine/alerts/api_fetcher.ex
lib/engine/alerts/fetcher.ex
lib/signs/utilities/signs_config.ex
test/engine/alerts/api_fetcher_test.exs
test/engine/alerts_test.exs

**Asana Ticket:** [Display individual bus route alerts](https://app.asana.com/0/1185117109217413/1204324618353138/f)
This is a bit of pre-work that came out of investigating the linked ticket. Calculates the list of route ids dynamically from the config, rather than hard-coding. This should ensure we're getting alerts for all bus routes, not just SL.

calculate all routes from signs json

---

lib/signs/utilities/messages.ex

**Asana Ticket:** [[bug] Single-line alerts at Ashmont lobby on top line](https://app.asana.com/0/1185117109217413/1205634330387875/f)
Left out single-line alert messages when we added in the early AM logic and the `flip?` function. These messages take up 24 characters and therefore need to be on the bottom line of the sign.
Screenshot of fix running locally:

Single line alerts on the first line of a MZ sign should trigger a flip

---

lib/signs/bus.ex
lib/signs/utilities/signs_config.ex
priv/signs.json
scripts/one_offs/bus_config.exs
test/signs/bus_test.exs

**Asana Ticket:** [Display individual bus route alerts](https://app.asana.com/0/1185117109217413/1204324618353138/f)
This changes the structure of bus config data so that it will be straightforward to add support for showing alerts for individual routes. This PR should _not_ change the behavior of the system.
Adds a new level of object to the JSON, called configs. Each config represents a distinct logical grouping of routes that the sign reports on. Configs contain sources, which describe which predictions (and in the future, alerts) to match for that config. Most configs have a single source, except for the signs where we aggregate multiple routes into a single message, e.g. the SL waterfront. This approach turns these aggregations into first-class concepts, so that the alert code will …

restructure bus configs to support route alerts

---

lib/jobs/message_latency_report.ex
lib/realtime_signs_web/controllers/monitoring_controller.ex

These manual runs currently run synchronously and the message latency report job appears to time out after a while if manually triggered via an HTTP request.
Judging from the logs, it looks like an automatic retry is triggered around the 1 minute mark which is probably killing the original process and preventing the job to run to completion which typically takes about 2 minutes. Then an error is finally returned to the client around the 2 minute mark which seems to suggest a 60 second default timeout from Phoenix for any given request. This seems to check out based off a few forum posts online. Rather than manually overriding this and extending the timeout, we can kick off the job as a background task and respond to the client immediately.

Manual runs of message log jobs as Tasks

---

lib/content/message/predictions.ex
lib/content/utilities.ex

**Asana Ticket:** [🟠🧑‍🤝‍🧑🔊 Text/Audio revisions](https://app.asana.com/0/1185117109217413/1205551289750420/f)
This PR makes some minor tweaks to the OL crowding logic.
- Crowding levels are now based off of occupancy percentages rather than occupancy status
- "some crowding" and "not crowded" train-level readouts are no longer used

OL crowding revision

---

priv/signs.json

**Asana Ticket:** [Investigate modifying headway destination based on (GL branch) service suspensions](https://app.asana.com/0/1185117109217413/1205572772013992/f)
In #663 we removed an old piece of logic that filtered predictions based off of the `routes` field in the source config. Now that that's gone, we don't need to do weird stuff in the `signs.json` file in order to get outlier predictions to show (ex. the occasional D train going down the Medford branch).
This change adjusts the routes fields for a handful of GL stations so that they accurately reflect what branches typically serve them. The change is also meant to set us up in anticipation of future logic for checking for downstream suspensions.

Fix GL routes in signs.json

---

lib/engine/routes.ex
lib/fake/httpoison.ex
lib/pa_ess/utilities.ex
lib/realtime_signs.ex
lib/signs/bus.ex
test/signs/bus_test.exs

**Asana Ticket:** [Add dynamic API calls for individual bus route alerts](https://app.asana.com/0/1185117109217413/1205660768174999/f)
This adds a new engine to dynamically pull bus route destinations from the API. It polls for new information every 30 seconds, and stores the result in ETS for quick lookups. In the unlikely event that a lookup fails (e.g. due to the API being down on startup), the downstream content generation will fall back on blank values.

fetch routes destinations from API

---

lib/signs/utilities/audio.ex

Temporarily enable crowding announcements on Back Bay and Tufts platforms for a field test on 10/24

Temporarily enable back bay and tufts

---

.github/workflows/dev-green.yml
.github/workflows/dev.yml
.github/workflows/prod.yml

This PR updates the deploy workflow to use v2 of the `deploy-ecs` workflow. This updated workflow assumes an IAM role instead of relying on long-lasting AWS keys for an IAM user
Successful deploy [here](https://github.com/mbta/realtime_signs/actions/runs/6631759657)

Chore: Update workflow to v2

---

lib/signs/utilities/predictions.ex

**Asana Ticket:** [Extend RL NB prediction filtering to JFK NB](https://app.asana.com/0/1185117109217413/1205861566055155/f)
Adds North Quincy northbound and JFK/Umass northbound to the existing red line filtering.

extend red line filtering to JFK

---

priv/signs.json

**Asana Ticket:** [Split Lechmere busway into two visual zones](https://app.asana.com/0/1185117109217413/1205857754053049/f)
Split the Lechmere busway into two visual zones that share the same audio zone.
Inner zone should show routes 69 and 80 and the outer zone should show route 87 and 88.

Split Lechmere into two visual zones

---

lib/engine/config.ex
lib/signs/utilities/messages.ex

**Asana Ticket:** [Add a Temporary Terminal mode in Signs UI](https://app.asana.com/0/1185117109217413/1205911324913693/f)
Adds handling of a new mode `:temporary_terminal` that will show predictions if there are any, and otherwise show headways.
If the sign is set to `:temporary_terminal` but the alert status does not indicate that the sign is at the boundary of an alert, t will default to `:auto` behavior.

Support Temporary Terminal mode

---

lib/content/message/predictions.ex
lib/engine/locations.ex
lib/fake/httpoison.ex
lib/locations/location.ex
lib/predictions/prediction.ex
lib/predictions/predictions.ex
lib/signs/utilities/predictions.ex
test/content/messages/predictions_test.exs
test/predictions/predictions_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Transition from 'consist' to `multi_carriage_details'](https://app.asana.com/0/1185117109217413/1205822469391764/f)
The transit data team is moving away from the `consist` field by mid December. We only use consist data to identify when a Red Line train so the migration doesn't have a major impact on us, but does mean that we need to fetch the same info from the locations feed now rather than directly from the predictions feed.

Migrate off of consist field

---

lib/engine/scheduled_headways.ex
test/engine/scheduled_headways_test.exs

**Asana Ticket:** [Revise display logic for departure/arrival times](https://app.asana.com/0/1185117109217413/1206103644850840/f)
Small change to add some resiliency to our schedules logic considering some weird data we saw from the API.

Default to arrival time for schedules

---

lib/content/audio/closure.ex
lib/content/message/alert/use_routes.ex
lib/signs/utilities/messages.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Adjust the default message for alerts that include Union Sq](https://app.asana.com/0/1185117109217413/1206049304225903/f)
Union Sq never gets shuttle service so OIOs have requested that we change Union Sq's default alert messaging to say
```
No Train Service
Use Routes 86, 87, or 91
```

Union Sq defaults to using custom alert messaging

---

priv/signs.json

**Asana Ticket:** [Add GL-NB to North Station concourse signs](https://app.asana.com/0/1185117109217413/1200592856846313/f)
Update the config for `green_north_station_commuter_rail_exit` to be like a mezzanine sign.

Add GL-NB to North Station concourse signs

---

lib/content/audio/vehicles_to_destination.ex
lib/pa_ess/utilities.ex
test/content/audio/vehicles_to_destination_test.exs
test/pa_ess/utilities_test.exs
test/signs/realtime_test.exs

This removes some old code for reading headways in Spanish, which is never called in practice. It's only active for Chelsea and South Station destinations, neither of which can come up in the rail code.

remove unused code for spanish headway readouts

---

.github/workflows/dev-green.yml
.github/workflows/dev.yml
.github/workflows/docker.yml
.github/workflows/prod.yml
Dockerfile
config/prod.exs
mix.exs

**Asana Ticket:** [migrate realtime-signs to Linux cluster](https://app.asana.com/0/1185117109217413/1205187491334062/f)
New Dockerfile and github actions for moving Realtime Signs to run on linux

Update dockerfile and actions

---

.github/workflows/dev-green.yml
.github/workflows/dev.yml
.github/workflows/docker.yml
.github/workflows/prod.yml
Dockerfile
config/prod.exs
mix.exs

Reverts mbta/realtime_signs#741

Revert "Revert "Revert "Revert "Update dockerfile and actions""""

---

lib/content/audio.ex
lib/content/audio/approaching.ex
lib/content/audio/boarding_button.ex
lib/content/audio/closure.ex
lib/content/audio/custom.ex
lib/content/audio/first_train_scheduled.ex
lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/no_service_to_destination.ex
lib/content/audio/passthrough.ex
lib/content/audio/stopped_train.ex
lib/content/audio/track_change.ex
lib/content/audio/train_is_arriving.ex
lib/content/audio/train_is_boarding.ex
lib/content/audio/vehicles_to_destination.ex
lib/content/message/alert/no_service.ex
lib/fake/unknown_audio.ex
lib/pa_ess/utilities.ex
test/content/audio/approaching_test.exs
test/content/audio/following_train_test.exs
test/content/audio/next_train_countdown_test.exs
test/content/audio/no_service_to_destination_test.exs
test/content/audio/passthrough_test.exs
test/content/audio/stopped_train_test.exs
test/content/audio/train_is_arriving_test.exs
test/content/audio/train_is_boarding_test.exs
test/content/audio/vehicles_to_destination_test.exs
test/pa_ess/utilities_test.exs

**Asana Ticket:** [RTS: Refactor audio messages to support TTS](https://app.asana.com/0/1185117109217413/1206141631184123/f)
Adds a new function to the Audio protocol to transform messages into TTS strings. This serves to formalize the various TTS fallback code that currently exists, and provides a unified interface that can be used with the new TTS system.
Notes:
* Most of these code paths won't be called currently, even the existing fallback ones, because we never generate the conditions that would cause them to be called.
* This implements the new simplified "train description" language via a common helper.
* Updates the fallback TTS with some newer features, like OL crowding.
* Fixes a small language bug in the station closure message.
* Cleans up some low-level tests for cases that …

add TTS audio format

---

lib/pa_ess/utilities.ex

**Asana Ticket:** [Add new (bus) audio for Brookline Village & Brookline Ave](https://app.asana.com/0/1185117109217413/1207093776768927/f)
Adds two new audio takes for "Brookline Ave" and "Brookline Village"
From the vendor:
> The TAKES have been added:
> 885 = Brookline Ave
> 886 = Brookline Village

Add new audio takes for Brookline Ave/Village

---

lib/engine/last_trip.ex

**Asana Ticket:** [Read in the "last train" information from transit data feed and display "end of service" information](https://app.asana.com/0/1185117109217413/1206605275887005/f)
Ad-hoc
Small tweak to track recent departures for 90 minutes instead of 60. This means that "Platform closed" will show for 90 minutes instead of 60. This is to help make sure that there is enough time for trips to pass through each stop so that MZ signs have a chance to show "Station closed".
60 minutes was too short so some stations at the ends of the OL and BL would never have their MZ signs show "Station closed" because the service ended status for one direction would be forgotten before the last trip in the other direciton reaches the station.

Track recent departure for 90 minutes

---

lib/content/message/last_trip/no_service.ex
lib/signs/utilities/last_trip.ex
test/signs/realtime_test.exs

Ad-hoc
Quick fix to prevent double-line paging on MZ signs during LTOTD treatment. This type of double paging causes a bug to occur in the vendor's software which leads to a crash and the signs going blank for some time.

Don't page no service message on MZ signs

---

lib/signs/utilities/messages.ex

This fixes a bug that was preventing custom mode from taking priority over LTOTD messages.

fix custom mode not overriding last trip message

---

lib/signs/utilities/predictions.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Update RTS filtering for non-revenue trains](https://app.asana.com/0/1185117109217413/1207429871853193/f)
This filters out predictions with `schedule_relationship` set to `SKIPPED`, to avoid displaying non-revenue predictions now that they include a departure time.

don't display predictions with skipped schedule_relationship

---

lib/signs/bus.ex
lib/signs/realtime.ex

This removes some unused `opts` parameters that were originally intended to be used in test cases. In practice, we just set the state directly, so these extra arguments are not used.

remove unused process options

---

lib/realtime_signs.ex

This fixes an intermittent crash on app startup. `Engine.Predictions` tries to access an ETS table controlled by `Engine.Locations`, and sometimes crashes one time if the process hasn't been initialized yet. By starting `Engine.Locations` first, it should avoid this problem. A similar situation applies to `Engine.LastTrip`.

reorder process startup to avoid race condition

---

lib/content/audio.ex
lib/content/audio/approaching.ex
lib/content/audio/boarding_button.ex
lib/content/audio/closure.ex
lib/content/audio/custom.ex
lib/content/audio/first_train_scheduled.ex
lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/no_service_to_destination.ex
lib/content/audio/passthrough.ex
lib/content/audio/service_ended.ex
lib/content/audio/stopped_train.ex
lib/content/audio/track_change.ex
lib/content/audio/train_is_arriving.ex
lib/content/audio/train_is_boarding.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_ess/utilities.ex
test/pa_ess/utilities_test.exs

This refactors the rail audio modules to support optional visual text to go along with TTS announcements. The default approach is to just paginate the same text used for TTS, but this can be customized later on a per-message basis.

add visual equivalent for rail TTS audio

---

lib/content/audio/service_ended.ex
lib/content/message/last_trip/platform_closed.ex
lib/content/message/last_trip/service_ended.ex
lib/content/message/last_trip/station_closed.ex
lib/signs/utilities/last_trip.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Modify "End of service" text to specify routes and/or directions](https://app.asana.com/0/1185117109217422/1207279074432055/f)
Updates Last Trip messages to add additional context w/r/t route or direction when possible.

Modify "End of service" text to specify routes and/or directions

---

lib/signs/utilities/last_trip.ex

**Asana Ticket:** [Investigate: weird LTOTD behavior on BL](https://app.asana.com/0/1205101743911491/1207509052653329/f)
We are seeing some weirdness on BL EB stops where we sometimes show "service ended" instead of "stopped away" for a train that is in the predictions feed as holding at an upstream station. While this change doesn't address the underlying problem with the data and trains potentially being mis-tagged (see ticket for more details on the investigation), we can mitigate the issue by making sure that stopped train messages don't get masked by LTOTD logic.

Consider stopped trains as a prediction

---

config/runtime.exs
lib/content/audio.ex
lib/content/message.ex
lib/pa_ess/scu_updater.ex
lib/pa_ess/updater.ex
lib/pa_ess/updater_api.ex
lib/pa_ess/utilities.ex
lib/realtime_signs.ex
lib/signs/bus.ex
lib/signs/utilities/audio.ex
test/signs/bus_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [RTS: Support communication with new SCU app](https://app.asana.com/0/1185117109217413/1206141631184125/f)
Implements the code path that sends messages to Scully, passing the audio strings through Watts first. Note that this code path is not expected to be used until we start converting stations, and there will be further changes before then. Notes:
* Currently, any unexpected response from Watts will the associated `Task` to crash, effectively skipping the entire message. This is a very coarse approach that we may want to tune up later.
* The `TODO` in the bus code is intended, for now. This will be implemented as a separate effort.
* This sets us up to be able to assert on the TTS strings in the high-level sign logic tests. That will be included in its own PR, since it …

enable communication with new SCU app

---

test/signs/realtime_test.exs

**Asana Ticket:** [RTS: Support communication with new SCU app](https://app.asana.com/0/1185117109217413/1206141631184125/f)
This adds assertions for all TTS audio outputs in the rail sign tests. There are no app code changes, so this serves to establish a baseline of the current behavior.

assert TTS audio in rail tests

---

lib/signs/utilities/source_config.ex
test/signs/realtime_test.exs

This adds route data to the sign structures in the tests, which makes them more reflective of the actual sign configs, and eliminates the need for a separate case for this.

add routes to test signs

---

lib/content/audio/service_ended.ex
lib/content/audio/vehicles_to_destination.ex
test/signs/realtime_test.exs

This fixes three audio issues:
1. When partial early AM suppression on a mezzanine sign results in two headway messages, the resulting combined message ends up with both a `destination` and `routes`. The headway TTS audio code wasn't accounting for that possibility, resulting in a crash.
2. In the same case as above, the non-TTS audio code was using a slightly different algorithm than the text code, resulting in a headway readout using the top line's destination, instead of the route name.
3. The TTS audio code for station-level service ended messages was still saying "This station is closed" instead of using the line name.

fix several audio issues

---

.gitignore
lib/pa_ess/utilities.ex
scripts/create-take.exs

**Asana Ticket:** [Configure busway signs for Rte 716](https://app.asana.com/0/1185117109217413/1207348699397552/f)
- adds headway abbreviation for "Cobbs Corner Canton"
- adds take IDs for new audio messages
- adds script to generate new audio WAV files using the AWS cli and `sox`

Configure busway signs for Rte 716

---

lib/engine/last_trip.ex

**Asana Ticket:** [Modify logic for LTOTD](https://app.asana.com/0/1185117109217413/1207279074432059/f)
Instead of expiring last trip ids and recent departures for 2 hours and 90 minutes respectively, we decided that it would be better to just lets Last Trip messaging stay up and then turn off all at once at 3:30am each day.

Clear Last Trip related data at 3:30am

---

priv/signs.json

**Asana Ticket:** ["BRD" showing on GL terminals too early](https://app.asana.com/0/1185117109217413/1207563461018197/f)
Sets `terminal: true` for  Riverside so when a prediction is 0 stops away `BRD` is not shown until within the predicted departure time.
Note: I still haven't reproduced the original issue locally. Any help verifying before merging is much appreciated.

fix: mark riverside as a terminal station

---

lib/signs/bus.ex
test/signs/bus_test.exs

**Asana Ticket:** [Support communication with new SCU app](https://app.asana.com/0/1185117109217413/1206141631184125/f)
This adds TTS versions of bus audio messages. These mirror the current audio message formats, except for the Spanish bridge message, which currently incorrectly shows English text.

add bus TTS audio

---

lib/pa_ess/http_updater.ex

**Asana Ticket:** [RTS update_signs: logs include message_type for custom or headway modes](https://app.asana.com/0/1185117109217413/1204643930705430/f)
- fetches sign config and includes message_type in `update_sign` logging

RTS update_signs: logs include message_type for custom or headway modes

---

lib/engine/config.ex
lib/engine/config_api.ex
lib/message_queue.ex
lib/pa_ess/http_updater.ex
lib/pa_ess/updater.ex
lib/signs/bus.ex
lib/signs/realtime.ex
priv/signs.json
test/engine/config_test.exs
test/message_queue_test.exs
test/pa_ess/http_updater_test.exs
test/signs/bus_test.exs
test/signs/realtime_test.exs

This adds a definition for a "test" sign(s) set up in our office. Other than the unique IDs, the config is a copy of `state_blue_mezzanine` for now.
Previously, if a sign wasn't configured in SignsUI, it would always be in the `off` mode. We'd like to be able to configure our new lab signs for testing without the complexity of supporting this unique "kind" of sign in SignsUI as well as this project.
This adds an optional `default_mode` field to sign configuration, which can be set to any of the "modes" supported by SignsUI. For now, this is only supported by `Realtime` (a.k.a. subway) signs and not `Bus` signs, but this would be easy enough to extend later if needed.
Due to now needing a sign's default mode as well as its ID whenever we want to determine its "current mode", this includes …

chore: add lab sign config

---

lib/signs/utilities/messages.ex
test/signs/realtime_test.exs

@PaulJKim pointed out that mezzanine signs when set to `:headway` mode check alert status but that code hadn't been updated to handle when alert statuses are different between `top` and `bottom` source configurations.
This change intercepts split alert status values passed to `get_alert_messages/2` and gets the highest priority alert status of the two using `Engine.Alerts.higher_priority_status/2` before continuing on to the existing implementation.

fix: handle split alert statuses for signs in headway mode

---

lib/signs/realtime.ex
lib/signs/utilities/messages.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Ashmont MZ sign shows headway mode for Mattapan Trolley when it's shuttling](https://app.asana.com/0/1185117109217413/1207563461018208/f)
different alert status per top/bottom config are needed to support showing an alert status based message on a single source config. this is most common when top and bottom source configs are for different lines/routes.
previously the alert_status for a sign was reduced down to a single value which could cause weird behavior when an alert was only effecting one of the two source configs.
https://github.com/user-attachments/assets/1ab76a7d-fe2e-4884-b0df-a1feb070402e

fix: expand handling of alert status on signs with top/bottom configs

---

lib/signs/realtime.ex

Defines `map_source_config/2`, a function for applying a function to SourceConfig values (both single and top/bottom--tuple).             
Uses the new `map_source_config/2` function to calculate `alert_status`, `first_scheduled_departures`, and `service_end_statuses_per_source`.

chore: refactor function application over `source_config` values

---

.github/PULL_REQUEST_TEMPLATE.md

**Asana Ticket:** ad-hoc
Added an additional item to the PR checklist. My understanding of `signs.json` is that the same content needs to live in both `signs_ui` and `realtime_signs`. This new item will help new contributors remember to update both.

chore: Add a step to template for signs.json changes

---

.envrc.template
config/runtime.exs
lib/content/message/predictions.ex
lib/fake/httpoison.ex
lib/predictions/last_trip.ex
lib/predictions/prediction.ex
lib/predictions/predictions.ex
lib/signs/utilities/predictions.ex
test/content/messages/predictions_test.exs
test/predictions/predictions_test.exs
test/signs/realtime_test.exs

Reverts mbta/realtime_signs#743
Unfortunately after deploying this migration last week, we started seeing some erroneous changes in predictions particularly with `BRD` predictions at terminals and passthrough announcements.
We should revert the migration for now to reduce the rider impact and to give us some space to do a deeper investigation into what could be causing the discrepancies in predictions when consuming the concentrate feeds vs the RTR feeds.

Revert "Migrate to GTFS-rt predictions and locations feeds"

---

priv/signs.json

The zone code that was actually set up for this sign turned out to be `n` rather than `m`. The second daisy-chained sign is also separately addressable as zone `s`, so we add a configuration for it too.
* `n` is a copy of `state_blue_mezzanine`
* `s` is a copy of `state_blue_eastbound`
- **Note:** I don't think these particular changes should actually be mirrored in Signs UI, since we don't want these signs to show up there.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207993019127452

chore: update lab sign definitions

---

priv/signs.json

The Harvard busway has been split into multiple child stops as of the 8/25/2024 rating. This adds those new child stops to the sources config of the Harvard upper busway sign.
**Asana Ticket:** [(RTS) New child stops added to Harvard Busway for 8/25 rating start](https://app.asana.com/0/1185117109217413/1208105531228653/f)
- https://github.com/mbta/signs_ui/pull/1402

config: add new child stops to harvard busway config

---

priv/signs.json

- https://github.com/mbta/signs_ui/pull/1403

fix: use strings for stop and route ids

---

lib/pa_ess/updater.ex

**Asana Ticket:** [Improve RTS and SCU message logging](https://app.asana.com/0/1185117109217422/1208067121004443/f)
This adds `audio`, `visual`, and `tag` fields to RTS message logs, with JSON-parseable visual data.
* Splunk should be able to parse the visual page data, allowing us to transform it easily in dashboards. (We'll want to deploy to dev-green and test in splunk to make sure this works as expected.)
* Legacy audio message logs now contain a human-readable representation of what was played. Note that for legacy stations (all of them currently), this data isn't exactly what's played, but it should be semantically equivalent. After migration, these logs will show exactly what was played.
* The random `tag` is not helpful for legacy stations, but after migration, SCUs will log this …

formalize logging of sign content and generate tags

---

lib/content/audio.ex
lib/content/audio/approaching.ex
lib/content/audio/boarding_button.ex
lib/content/audio/closure.ex
lib/content/audio/custom.ex
lib/content/audio/first_train_scheduled.ex
lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/no_service_to_destination.ex
lib/content/audio/passthrough.ex
lib/content/audio/service_ended.ex
lib/content/audio/stopped_train.ex
lib/content/audio/track_change.ex
lib/content/audio/train_is_arriving.ex
lib/content/audio/train_is_boarding.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_messages/pa_message.ex
lib/signs/bus.ex
lib/signs/realtime.ex
lib/signs/utilities/audio.ex

**Asana Ticket:** [Improve RTS and SCU message logging](https://app.asana.com/0/1185117109217413/1208067121004443/f)
* Switches to explicit logging of extra message metadata, instead of dumping the raw struct. This effectively removes a lot of fields that were initially intended for debugging, but now that we're including visual and audio strings with every message, most of them should be unnecessary. This approach will let us add additional metadata easily, if desired.
* Keeps the PA message metadata needed for the playback dashboard, but renames them `pa_message_id`, `pa_message_priority`, and `pa_message_interval` to avoid confusion
* Unifies the PA message playback code, for simplicity and to allow bus sign logs to inherit the same rich log output.

streamline message logging

---

.github/workflows/dev-green.yml

**Asana Ticket:** [[extra] remove auto-deploy for RTS dev-green](https://app.asana.com/0/1185117109217413/1208381515035004/f)
Automatic deploys to dev-green upon pushing to main can cause unintentional hindrances when using dev-green to test branches. This change to the workflow makes it so that we can only manually deploy to dev-green.

Don't deploy to dev-green on push to main

---

lib/content/audio/passthrough.ex

This restores the trip_id logs for passthrough audios, for the purpose of debugging RTS/Concentrate data.

log trip_id for passthrough audios

---

priv/signs.json

**Asana Ticket:** [Fix up Harvard busway berth assignments](https://app.asana.com/0/1185117109217413/1208334278718315/f)
Updated Harvard upper busway config to account for new berth assignments.

chore: Adjust Harvard upper busway config with new child stops/routes.

---

lib/content/audio/closure.ex
lib/content/audio/service_ended.ex
lib/content/audio/vehicles_to_destination.ex
lib/content/message/alert/destination_no_service.ex
lib/content/message/alert/no_service.ex
lib/content/message/alert/no_service_use_shuttle.ex
lib/content/message/headways/paging.ex
lib/content/message/headways/top.ex
lib/content/message/last_trip/no_service.ex
lib/content/message/last_trip/station_closed.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/early_am_suppression.ex
lib/signs/utilities/headways.ex
lib/signs/utilities/last_trip.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex
lib/signs/utilities/source_config.ex
test/content/audio/closure_test.exs
test/content/messages/headways/top_test.exs

This is a small refactor in advance of a larger one. Several of the `Message` structs carry a `routes` field which holds the list of routes from the config used to generate it. However, at the end of the computation, the only thing we care about is whether there was a single unique route. This changes the fields to hold a single `route`, or nil if there were multiple, which simplifies downstream calculations. It also adds a `route` field to a few additional messages, which will be used by later changes.

pass single route through messages

---

lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
lib/content/utilities.ex
lib/signs/utilities/predictions.ex
test/content/messages/predictions_test.exs
test/content/messages/stopped_train_test.exs
test/content/utilities_test.exs
test/signs/realtime_test.exs

This change is in support of an larger refactor. It removes some soft error handling in `destination_for_prediction`, simplifying the callers. This code has been stable for a long time, and the logs show no indication that it ever fails during normal operation. Going forward, any unexpected predictions would cause this to fail loudly, which seems like a decent approach.

streamline prediction destination code

---

lib/content/audio/no_service_to_destination.ex
lib/content/message/alert/destination_no_service.ex
lib/content/message/alert/no_service.ex
lib/content/message/last_trip/no_service.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/last_trip.ex

This is a small refactor in advance of a larger one. Adds two new message variants:
* A short version of the single-line destination-specific "no service" message, which can fit on the top line.
* A destination-specific version of the full-page "no service" message.
Note that neither of these messages are used yet, but they will be in a followup PR. The language has been ok'd by product.
Also reworks the `line` field in the "service ended" message as `variant`, to make it more general.

add alert message variants

---

priv/signs.json

**Asana Ticket:** [Fix up Harvard busway berth assignments (again)](https://app.asana.com/0/1185117109217413/1208530330455995/f)
This modifies the sign config according to the above ticket.

adjust harvard busway config

---

lib/signs/utilities/predictions.ex
lib/signs/utilities/source_config.ex
priv/signs.json
scripts/one_offs/terminal_config.exs
scripts/one_offs/zone_mapping.exs
test/signs/realtime_test.exs
test/signs/utilities/source_config_test.exs

This moves the `terminal` flag from the individual source object to the config object. This is a more natural way to model this information, and all instances of this flag were identical across all sources within each config. This simplifies lookup of this information during the main logic loop.
The `signs.json` transformation was done programmatically, and the script is included for review.
Also includes a small unrelated script that performs some zone mapping analysis.

move terminal flag to source config object

---

lib/content/audio/approaching.ex
lib/content/audio/train_is_arriving.ex
lib/pa_ess/utilities.ex
test/pa_ess/utilities_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Adjust Approaching/Arriving messages](https://app.asana.com/0/1207660975981504/1208551608056344/f)
This adjusts the visual component of the post-migration approaching and arriving messages to a more compact form that fits one one page. This should provide a close match for what currently plays pre-migration.

adjust approaching and arriving visual messages

---

lib/content/audio/approaching.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/train_is_arriving.ex
lib/content/message/predictions.ex
lib/content/utilities.ex
lib/signs/utilities/predictions.ex
lib/signs/utilities/source_config.ex
priv/signs.json
scripts/one_offs/platform_config.exs
test/content/messages/predictions_test.exs
test/signs/realtime_test.exs
test/signs/utilities/source_config_test.exs

This moves the `platform` field out of the sign configuration and into code. The platform is only non-nil in two specific cases, and can be straightforwardly computed from the stop id, so there's no reason to store it separately.
The `signs.json` change was made programmatically, and the script is included for review.

move platform config out of signs.json

---

lib/content/audio/service_ended.ex
lib/content/message/early_am/destination_scheduled_time.ex
lib/content/message/early_am/destination_train.ex

**Asana Ticket:** [Lower case "g" in "Oak grove due" should be capitalized](https://app.asana.com/0/1185117109217422/1208591545042708/f)
`String.capitalize` lowercases the remainder of the string, which is usually not what we want. These usages are unnecessary anyway, since the destination names already have the right casing.

fix capitalization of early AM messages

---

lib/signs/utilities/predictions.ex
lib/signs/utilities/source_config.ex
priv/signs.json
test/signs/realtime_test.exs
test/signs/utilities/source_config_test.exs

This is a small behavior change that was ok'd by product. There was some old logic that would detect a case where `ARR` would be shown on both lines, and tweak the display so the second line said `1 min` in all but a handful of cases. We're not exactly sure of the original rationale, but suspect it was to smooth over a data quality issue. The data should be better now, and also this special handling creates an inconsistency with other touchpoints, so we'd like to remove it.

don't modify predictions when both lines ARR

---

lib/content/audio/approaching.ex
lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/stopped_train.ex
lib/content/audio/train_is_arriving.ex
lib/content/audio/train_is_boarding.ex
lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/messages.ex
test/content/audio/following_train_test.exs
test/content/audio/stopped_train_test.exs
test/content/messages/predictions_test.exs

Prediction and stopped-train messages, unsurprisingly, end up needing most of the fields from the underlying prediction. This stores a reference to the prediction struct itself, rather than copying each individual field, which simplifies the representation and reduces boilerplate. Also inlines the `width` parameter, which never actually varies.

reference prediction directly and remove individual fields

---

lib/engine/config/headway.ex
test/engine/config/headway_test.exs

**Asana Ticket:** [Change RTS to read these new values, handle appropriately](https://app.asana.com/0/1185117109217413/1208512927678681/f)
This supersedes #837 after we realized that the requirements weren't quite right. Switches to reading the new headway periods.

use new headway periods

---

lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/train_is_boarding.ex
lib/content/message/predictions.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex
test/content/audio/following_train_test.exs
test/content/audio/next_train_countdown_test.exs
test/content/messages/predictions_test.exs

This refactors the creation of prediction messages to unify the `terminal` and `non_terminal` code paths, since they're more similar than different. It also introduces a new `special_sign` field to encode various special case behaviors without having to check against station code/zone repeatedly.

unify prediction message constructors

---

.github/PULL_REQUEST_TEMPLATE.md

Once mbta/signs_ui#1445 lands, `signs_ui` will incorporate this repo's `signs.json` via a dependency instead of a copy of the file. This updates the PR checklist accordingly.

doc: update PR checklist

---

lib/content/audio.ex
lib/pa_ess/updater.ex
lib/signs/bus.ex
test/signs/bus_test.exs

**Asana Ticket:** [Change voice and parameters used when generating Spanish audio, and use updated Spanish TTS content](https://app.asana.com/0/1185117109217413/1208634633982700/f)
This changes the Spanish bridge message as outlined in the ticket, using the "Mia" voice. Adds the appropriate SSML wrapper around all audio messages.
Note that we're generating accented characters, but the sign is not capable of displaying them. This will be followed by a Scully PR to strip accents during display.

modify Spanish voice and bridge message

---

lib/content/message/predictions.ex
test/content/messages/predictions_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Remove 60-second buffer at terminals](https://app.asana.com/0/1185117109217422/1208776052650232/f)
This removes the 60 second offset for terminal predictions. The original reasons for this aren't entirely clear, but we think it's no longer necessary, and removing it will improve consistency across touchpoints.

don't offset terminal predictions

---

lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex

This refactors the prediction filtering logic so that all processing happens in one central place, and is done on the predictions themselves (as opposed to filtering messages). This makes it easy to understand exactly how predictions are modified before display, and paves the way for further refactoring.

centralize prediction preprocessing

---

lib/content/audio/first_train_scheduled.ex
lib/content/audio/following_train.ex
lib/content/audio/next_train_countdown.ex
lib/content/audio/no_service.ex
lib/content/audio/service_ended.ex
lib/content/audio/stopped_train.ex
lib/content/audio/train_is_boarding.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/source_config.ex
test/pa_ess/utilities_test.exs
test/signs/utilities/source_config_test.exs

This removes some fallback code dealing with destination names, which is never actually needed in practice, because we can produce content for all supported destinations. This simplifies the calling code. Adds `destination_var` values for Chelsea and South Station for completeness (though they are not strictly required, since we don't use those destinations from the rail code, and the bus code has its own way of handling that).

remove unused fallbacks for destination utils

---

lib/pa_ess/utilities.ex
priv/signs.json

**Asana Ticket:** [[add-on] signs config updates for BNR](https://app.asana.com/0/1185117109217413/1208888264202011/f)
Adds route 109 to the harvard upper busway as well as new audio for this route and its headsign.

Add new bus route for BNR

---

lib/content/audio/no_service.ex
lib/content/message/alert/use_routes.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Update text for union square shuttles](https://app.asana.com/0/1185117109217413/1208671287188515/f)
Route 86 will no longer service Union Square after the Bus Network Redesign, and be replaced at Union Square by Route 109.

Update text for Union Square Shuttles to replace 86 with 109

---

priv/signs.json

**Asana Ticket:** [Fix up Harvard upper busway stops (third time's the charm!)](https://app.asana.com/0/1185117109217413/1208983261541535/f)
Fix stop ids after BNR initial launch

Fix harvard upper busway stop ids

---

lib/content/message/predictions.ex
test/content/messages/predictions_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Change terminals "BRD" time to 60 seconds](https://app.asana.com/0/1185117109217422/1208885272304851/f)
When a train is at the terminal, this will change sign from displaying "1 min" to "BRD" when the departure time prediction goes below 60 seconds.

Change time to display "BRD" to <60 seconds until departure at terminals

---

lib/monitoring/uptime.ex

**Asana Ticket:** [Process ARINC JSON for LivePA connectivity into Splunk](https://app.asana.com/0/1185117109217413/1208851406631730/f)
After deploying the initial change, we lost logging of some device types. I think this is due to the description screen for these devices only having three parts to them rather than 4. Oddly, I'm not able to find any `MatchError` logs in Splunk which is what I would expect, but the `Endpoint` process is crashing every 2 minutes which is the cadence at which we receive device status logs.

[bugfix] Account for 3-part node descriptions

---

lib/content/audio/next_train_countdown.ex
lib/content/message/platform_prediction_bottom.ex
lib/content/message/predictions.ex
lib/content/message/stopped_train.ex
lib/pa_ess/utilities.ex
lib/signs/utilities/audio.ex
lib/signs/utilities/predictions.ex
test/signs/realtime_test.exs

This extracts several helpers related to predictions, as a part of the larger message refactoring effort. Notes:
* Removes special handling of "approaching" predictions, since only the audio path cares about them.
* Unifies the logic for determining "approximate" minute values, fixing some potential edge cases.
* Fixes a rare historical edge case where approaching predictions wouldn't be read out during the normal read loop.
Aside from these few cases, the overall system behavior should be unchanged.

extract prediction helpers

---

lib/engine/pa_messages.ex
lib/signs/bus.ex
lib/signs/realtime.ex
lib/signs/utilities/audio.ex
test/engine/pa_messages_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Revise RTS to remove PA Message bottleneck failures in Legacy PA/ESS](https://app.asana.com/0/1185117109217413/1208950993234729/f)
This changes the playback code for PA messages to send a single aggregate message to all targeted zones within a station, instead of individual per-sign messages. This involves moving the responsibility for playback into the PA message engine, and having the signs just provide their configs (and continue to track playbacks in order to guard against accidental duplicates).

aggregate PA message playback

---

lib/message.ex
lib/message/alert.ex
lib/message/custom.ex
lib/message/empty.ex
lib/message/first_train.ex
lib/message/headway.ex
lib/message/predictions.ex
lib/message/service_ended.ex
lib/signs/utilities/headways.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/predictions.ex

This introduces a new `Message` protocol and associated structs as part of the ongoing refactoring effort. These new structs represent a piece of sign content at a purely semantic level, in contrast with the existing `Content.Message` structs which encode more concrete, line-level content. The new protocol allows these abstract messages to be "rendered" into various concrete visual (and eventually audio) forms.
Conceptually, message generation is broken into several steps: First, generate the abstract messages to display. Then, optionally transform these messages, e.g. to combine headway or alert statuses. Finally, render the messages into actual line content, including flipping, shortening, or paging as needed.
One immediate benefit of this change is that the message generation algorithm …

introduce Message structs

---

lib/content/audio/passthrough.ex
lib/signs/utilities/predictions.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Use "Southbound" instead of Ashmont/Braintree for non-revenue trains](https://app.asana.com/0/1185117109217413/1208651243993394/f)
Adds take `891` which announces Ashmont and Braintree Red Line passthroughs as "Southbound". Also adjusts the TTS codepaths to do the same.

Use "Southbound" for Red Line non revenue trains

---

lib/pa_ess/utilities.ex
lib/predictions/prediction.ex
lib/predictions/predictions.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Special message for 4car RL consists](https://app.asana.com/0/1185117109217422/1209181549811302)
This attaches the `multi_carriage_details` field from the location struct to the prediction, so we can use it for checking for 4-car trains and new Red Line cars. This is straightforward because we already look up the location data when generating each prediction.

add carriage details to prediction

---

lib/content/audio/predictions.ex
lib/message/predictions.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Change timing/existence of approaching/arriving messages](https://app.asana.com/0/1185117109217413/1209206869122456)
This is a precursor to changing the structure of approaching/arriving announcements. Previously we borrowed the arriving/boarding announcement audios when generating passive readouts of predictions with those statuses. This changes to use a special, passive phrasing for this, which also doesn't include the (extraneous) visual component.
Note that this will almost never actually happen in practice, because the transition to those states will generate the corresponding announcement, which will then _delay_ passive readouts (typically until that status is over). However, this change will allow us to delete the arriving announcement code shortly. Product has …

passive readout for ARR/BRD

---

lib/content/audio/approaching.ex
test/content/audio/approaching_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Change timing/existence of approaching/arriving messages](https://app.asana.com/0/1185117109217413/1209206869122456)
This is a preliminary change in support of both the approaching/arriving consolidation and the new four-cars announcements. It unifies the code paths for creating approaching audio, and removes some extraneous checks. Note that while this removes some RL-specific guards in this code, the upstream code already does a similar restriction, so the end result is the same.
The slight change in output is the result of adding an extra space to the message for consistency, which shouldn't have any visible impact after the message is formatted.

streamline approaching announcement

---

lib/content/audio/approaching.ex
lib/pa_ess/utilities.ex
test/content/audio/approaching_test.exs
test/pa_ess/utilities_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Switch to Polly approaching messages and add yellow line message](https://app.asana.com/0/1185117109217413/1209206869122457)
This switches to the new polly-generated audio takes for approaching messages. Includes the following behavior changes:
* Uses the new standard "[destination] train" phrasing
* Includes both platform and "new cars" modifiers if applicable
* The migrated code no longer does custom formatting, for a closer match with the ARINC behavior (we can change this later).

use new audio takes for approaching message

---

lib/pa_ess/utilities.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Prevent predictions from skipping approaching messages](https://app.asana.com/0/1185117109217413/1209370907571522)
Modified approaching announcement window from 30-45 to 0-45 seconds
- Fixed tests associated with it, now calls approaching message with two ARR on a sign

Modified approaching announcement window from 30-45 to 0-45 seconds

---

lib/content/audio/approaching.ex
test/content/audio/approaching_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [Add "platform edge" message](https://app.asana.com/0/1185117109217413/1209206869122457)
This adds a "Please stand back" message onto the approaching announcement.

add platform edge message to approaching announcement

---

.github/workflows/elixir.yml

The old version of the `cache` action is deprecated and failing.

upgrade github action versions

---

lib/content/audio/approaching.ex
lib/content/audio/boarding_button.ex
lib/content/audio/first_train_scheduled.ex
lib/content/audio/no_service.ex
lib/content/audio/passthrough.ex
lib/content/audio/predictions.ex
lib/content/audio/service_ended.ex
lib/content/audio/track_change.ex
lib/content/utilities.ex
lib/pa_ess/utilities.ex
lib/signs/bus.ex
test/content/audio/track_change_test.exs
test/pa_ess/utilities_test.exs

This fully standardizes the handling of audio take ids. All take ids are now produced by the `audio_take` function, which maps a semantic-but-readable identifier to the corresponding numeric take id. The higher-level `audio_message` can now optionally produce `:audio_visual` messages, allowing it to take over the remaining cases that were not already using this pattern.

refactor take messages

---

lib/content/audio/predictions.ex
lib/message/predictions.ex
lib/signs/utilities/audio.ex

**Asana Ticket:** [Only announce 4-car trains for next trains, not following trains](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1209554302146849)
Only include the 4-car messaging when the announcement is for the next train, not the following train.

Don't announce 4 cars when following train

---

lib/content/audio/approaching.ex

**Asana Ticket:** [Omit the "all new Red Line cars" portion of the message if it is a 4-car train](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1209554302146846)
Don't announce "All new Red Line cars" if it's a 4-car train.

Omit new cars message when 4 car train

---

lib/engine/alerts.ex
lib/engine/alerts/fetcher.ex
lib/signs/realtime.ex
test/engine/alerts_test.exs
test/signs/realtime_test.exs

**Asana Ticket:** [All destinations must be in alert mode to trigger alert status](https://app.asana.com/0/1185117109217413/1208776052650234/f)
This change makes it so that instead of using a sign's "maximum alert status", we use the "minimum alert status". This effectively makes it so that we prefer to show less information rather than more in cases where there are > 1 alert statuses for a given sign.
A couple nuances to the change:
- We should be able to remove the consideration of `overall_route_status` when calculating the minimum alert status. Based on the logic in `lib/engine/alerts/api_fetcher.ex`, routes only receive the status `:alert_along_route` and that alert status isn't useful to us.
- I reordered the alert status priorities based on the principal that more information = …

Use minimum alert status

---

lib/content/audio/train_is_boarding.ex
lib/pa_ess/utilities.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Add a 4-car train piece to the "boarding" message at Alewife/Braintree](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209846410769747?focus=true)
- "It is a shorter 4-car train. You may have to move to a different part of the platform to board."
- Added four car special messaging specifically for Braintree and Alewife when passengers are boarding
- Waiting on the take ID from ARINC

Added special four car boarding message for Braintree/Alewife

---

.github/workflows/elixir.yml
lib/pa_ess/updater.ex

**Asana Ticket:** [SCU audio and visual fixes](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209953188678181?focus=true)
This changes the audio generation from `mp3` to `pcm`, to go with the corresponding change in Scully.

switch to PCM audio generation

---

lib/content/audio/first_train_scheduled.ex
lib/pa_ess/utilities.ex
test/content/audio/first_train_scheduled_test.exs

**Asana Ticket:** [Early AM language - use "departs" instead of "arrives" at terminals](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209805150516630?focus=true)
Use "departs at" instead of "scheduled to arrive at" for any early AM audio announcements.
This makes more sense at terminals and also generally since the time that we show/announce to riders is the first scheduled _departure_, not arrival.

Use departs at instead of scheduled to arrive at

---

lib/engine/predictions.ex
lib/predictions/predictions.ex
test/predictions/predictions_test.exs

`Engine.Predictions` occasionally crashes because the API returns a 200 response with a non-JSON body. This makes the code resilient against that case, so we'll just log a warning instead.

make predictions engine resilient to bad json

---

lib/engine/bus_stops.ex

**Asana Ticket:** [Easier configuration for bus PA/ESS](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1208977593203660?focus=true)
Quick fix for a bug in #913. When there's an error while fetching from the v3 API, we should return `{:noreply, state}` and not just an empty list.

Return proper message when error while fetching bus schedules

---

lib/engine/alerts.ex
test/engine/alerts_test.exs

**Asana Ticket:** [No Service Alert handling at Terminal ](https://app.asana.com/1/15492006741476/project/1208877354406742/task/1210060535858857?focus=true)
With the change to use the minimum alert status for all stop IDs at a station, a bug was introduced with terminal station `stop_ids` that do not receive Alerts. To get around this, added logic to filter these out before determining the minimum alert status for a station.

bugfix: Do not include platform stop_ids when finding min alert at terminal stations

---

.envrc.template
.tool-versions
Dockerfile
config/runtime.exs
lib/engine/config.ex
lib/engine/health.ex
lib/engine/scheduled_headways.ex
mix.exs
test/engine/health_test.exs
test/engine/locations_test.exs
test/engine/network_check/hackney_test.exs
test/support/helpers.ex
test/test_helper.exs

* Address warnings regarding charlist syntax. In some cases these could have just been binaries; in others (Erlang APIs) chars are necessary.
* Address test failures from not having `inets` loaded. This now needs to be in `extra_applications` for certain `httpd` functions to exist; starting it "manually" in `test_helper.exs` no longer works.
* Use Erlang Alpine image as the base for the runtime container instead of plain Alpine, so it already has the proper packages installed and we don't have to maintain the list ourselves.

chore: update Erlang and Elixir versions

---

lib/pa_ess/utilities.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Investigate/Fix BRD->ARR issue](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209953188678168?focus=true)
Temporary stop-gap for BRD to ARR issue until we have a better, more definitive way to know when a train is boarding.

Add temporary fix for BRD to ARR issue

---

lib/content/audio/track_change.ex
lib/pa_ess/utilities.ex
test/content/audio/track_change_test.exs

**Asana Ticket:** [RTS: Review/update Park St track change info](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210238696309072?focus=true)
Update track change logic so that:
1. B and D are considered opposite platforms
2. C and E are considered opposite platforms
3. Track change audio uses the "piecemeal" approach

Update track change

---

priv/signs.json

**Asana Ticket:** https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209896617242906
Bus signs were previously given a read loop of 6 minutes, or 7 minutes for Nubian station. For better accessibility we'd like to reduce this to 4 minutes (240 seconds) across the board, the same as subway signs.
This also adjusts read loop offsets to avoid playing overlapping audio within the same busway.
* With two readouts, offsets are 120 seconds apart.
* With three readouts, offsets are 80 seconds apart.
* For Nubian, which has 5 distinct readouts, offsets are 45 seconds apart (sacrifices a bit of airtime to create more "round" numbers; exact division would be 48 seconds). The two readouts which share the same audio zone (`c`, for platforms A and C) are 90 seconds apart.
I tried to …

feat: shorten busway audio readout intervals

---

lib/pa_ess/updater.ex
priv/signs.json

**Asana Ticket:** [Middleware: Batch encode sign and device data](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210475118985495?focus=true)
This switches to the new API format for Scully, and sends a single zone list including the station code. Also fixes a few incorrect SCU references, noticed during hardware encoding.
This change will need to be deployed simultaneously with mbta/scully#98

send single zone to scully

---

lib/content/audio/predictions.ex
lib/message/predictions.ex
lib/signs/utilities/messages.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Don't say "Platform TBD" when one branch is shut down](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209896617242902?focus=true)
Changes behavior for the JFK/UMass mezzanine to only show an Alewife prediction as (TBD) when we have at least one prediction for each platform AND the prediction in question is >5 minutes away. If we only have predictions for one of the two platforms, this now shows the platform regardless of the time.

feat: JFK mezzanine does not show TBD platform when all upcoming predictions to Alewife are for the same platform

---

lib/engine/scheduled_headways.ex
lib/pa_ess/utilities.ex
lib/signs/bus.ex
lib/signs/utilities/headways.ex
priv/signs.json
test/signs/bus_test.exs

**Asana Ticket:** [Actual headway mode on Silver Line signs](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1207891972773461?focus=true)
Building off of @robbie-sundstrom PR here: https://github.com/mbta/realtime_signs/pull/933
- Added headway mode for Silver Line buses for platform/mezzanine modes
- For headways on the silver line, we'll now show "Silver Line Buses/Every x to y min" and "Buses to [dest]/Every x to y min".
- Mezzanine (currently seems like just to WTC) will show headways separately until both configs are in headway mode in which case we'll display the "Silver Line Buses" messaging (n.b. currently, at least in my dev-green configuration there doesn't seem to be predictions for WTC Mezz sign to begin with. Will look into)
- Chelsea Bridge paginates …

Silver Line Headways

---

priv/signs.json

**Asana Ticket:** [Fix: Courthouse Mezzanine Sign only shows inbound predictions/headway](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210891029468366?focus=true)
This is deployed to dev-green, so you can see this configuration working in Signs UI there: https://signs-dev-green.mbtace.com/viewer

fix: Configure Courthouse mezz sign to show both inbound + outbound stops

---

lib/content/audio/passthrough.ex
lib/content/utilities.ex
lib/pa_ess/utilities.ex
lib/signs/realtime.ex
lib/signs/utilities/predictions.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Fix PA/ESS GL pass-through destination announcements](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1210661130574832?focus=true)
This modifies passthrough announcements to always use the config's "headway destination" instead of the prediction destination, which will result in directional destinations being used at all trunk stops where there isn't an unambiguous anchor station. We also skip announcing GL branch letters, mostly to avoid improper phrases like "The next D train to Eastbound". As a result, even places where we do have an anchor will now say e.g. "The next Riverside train" for passthrough messages, which seems fine since the branch letter is irrelevant if you can't board the train.

adjust passthrough messaging

---

priv/signs.json
scripts/one_offs/mezzanine_announcements.exs

**Asana Ticket:** [Only Play Approaching Messages on Platforms](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210643067506405?focus=true)
This reconfigures all mezzanine signs to not generate approaching or boarding announcements. The change was made via script, which is included for review.

remove mezzanine announcements

---

priv/signs.json

Stop 71199 is the Green Line eastbound fence track at Park Street. This platform can only be used by service terminating at Park Street, since the tracks physically do not allow continuing on to Government Center; passengers would never be allowed to board a train here. Despite this, due to an ongoing data issue, predictions will sometimes be published with a departure time for this stop (suggesting the train will accept passengers). This results in signs confusingly showing a "Park Street" departure *at* Park Street.
Prior to the underlying data issue being fixed, we can address this by removing the stop from sign configurations entirely.
**Asana Ticket:** https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211023799958882

fix: never show Park St departures at Park St

---

lib/pa_ess/utilities.ex
lib/signs/bus.ex
test/signs/bus_test.exs

"SIlver Line" text for Seaport/Silver Line Outbound buses have been changed to be "SL Outbound". The audio will still be "Silver Line" but added an "Outbound" after it. 
**Asana Ticket:** [Add "Outbound" to SL MZ/Platform Signs ](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1210728892258435?focus=true)

Changed Silver Line to SL Outbound for PA/ESS message/audio

---

lib/engine/config.ex
lib/fake/ex_aws.ex
lib/fake/external_config/local.ex
lib/signs/utilities/messages.ex
lib/signs/utilities/source_config.ex
priv/config.json
test/engine/config_test.exs
test/external_config/local_test.exs
test/external_config/s3_test.exs
test/signs/bus_test.exs
test/signs/realtime_test.exs

It's no longer possible to set a sign to this mode in Signs UI. The previous use of this mode, to suppress the display of predictions, is now fulfilled by the Prediction Suppression tool in Screenplay.
**Asana Ticket:** https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210858867684207

chore: remove support for headway mode

---

lib/engine/config/headway.ex
test/engine/config/headway_test.exs

**Asana Ticket:** [RTS Timezone Offset = Inconsistent Headway Values on SL DUPs + PA/ESS](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211228746535321?focus=true)
Fixed a bug where the Bus Headways was using UTC to grab the Headway values instead of the correct EST/EDT timezone.
Also switched the `current_time_period` function to be a 4am service day end rather than 3am.

Fixed Headway Timezone bug for Bus Times

---

lib/pa_ess/utilities.ex

**Asana Ticket:** [Add SL Eastbound Transitway headsigns to RTS](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1208484126045844?focus=true)
This adds the missing `Design Ctr` abbreviation, and updates the `SL Way` one.

add SL eastbound abbreviations

---

lib/content/audio.ex
lib/content/audio/approaching.ex
lib/content/audio/boarding_button.ex
lib/content/audio/custom.ex
lib/content/audio/first_train_scheduled.ex
lib/content/audio/no_service.ex
lib/content/audio/passthrough.ex
lib/content/audio/predictions.ex
lib/content/audio/service_ended.ex
lib/content/audio/track_change.ex
lib/content/audio/train_is_boarding.ex
lib/content/audio/vehicles_to_destination.ex
lib/pa_ess/utilities.ex
lib/pa_messages/pa_message.ex
lib/signs/bus.ex
lib/signs/utilities/audio.ex
test/signs/realtime_test.exs

**Asana Ticket:** [Announcement messages on short displays in new PA/ESS MW](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211262872771663?focus=true)
- Added support for short signs in cases we have short SCUs by explicitly paginating text in our TTS audio
- In announcements where we were paginating previously, now we have a text_length parameter that is :short or :long depending on if the sign is part of a list of short signs. :short announcements are paginated based on a smaller length (18) as opposed to the default 24
- Added tests and a helper module to define sign lengths

Support short signs for paginated text in announcements
